import {
  Activity,
  Ambulance,
  Archive,
  Brain,
  ClipboardList,
  HeartPulse,
  Image,
  Microscope,
  ShieldPlus,
  SquareActivity,
  Stethoscope,
  Syringe,
} from 'lucide-react'
import { implementedLegacyPaths } from '@/config/legacy-functional-map'
import type { ModuleDefinition, ScreenPattern } from '@/types/navigation'
import type { WorkspaceKey } from '@/types/auth'

export const screenPatternLabels: Record<ScreenPattern, string> = {
  'filters-table': 'Filtros + tabla',
  'filters-chart-table': 'Filtros + grafico + tabla',
  exporter: 'Exportador',
  'modal-detail': 'Detalle con modal',
}

export const workspaceMeta = {
  main: {
    label: 'Reporteador',
    shortLabel: 'Reporteador',
    basePath: '/app',
  },
  sigh: {
    label: 'Datos en Linea',
    shortLabel: 'Datos en Linea',
    basePath: '/sigh',
  },
} as const

function createModule(definition: ModuleDefinition): ModuleDefinition {
  return definition
}

function scaffoldModule(definition: Omit<ModuleDefinition, 'implemented' | 'priority' | 'summary'> & { summary?: string }) {
  const implemented = implementedLegacyPaths.has(definition.path)

  return createModule({
    implemented,
    priority: implemented ? 'alta' : 'posterior',
    summary:
      definition.summary ??
      (implemented
        ? 'Migrado desde el legacy como acceso funcional dentro de la nueva arquitectura.'
        : 'Acceso preservado del menu actual para mantener continuidad operativa.'),
    ...definition,
  })
}

const defaultGoals = ['Mantener visible este acceso dentro del menu actual.', 'Preparar su pantalla operativa dentro de la nueva shell.']

export const mainModules = [
  scaffoldModule({
    key: 'main-consulta-externa',
    legacyModule: 'upss',
    legacyRoute: '/upss/producciong',
    workspace: 'main',
    path: 'atencion-ambulatoria-hospitalizacion/consulta-externa',
    label: 'Consulta Externa',
    title: 'Consulta Externa',
    section: 'Departamento Atencion Ambulatoria y Hospitalizacion',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Stethoscope,
  }),
  scaffoldModule({
    key: 'main-consulta-externa-servicio',
    legacyModule: 'upss',
    legacyRoute: '/upss/produccionec',
    workspace: 'main',
    path: 'atencion-ambulatoria-hospitalizacion/consulta-externa-por-servicio',
    label: 'Consulta Externa por Servicio',
    title: 'Consulta Externa por Servicio',
    section: 'Departamento Atencion Ambulatoria y Hospitalizacion',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Stethoscope,
  }),
  scaffoldModule({
    key: 'main-consulta-externa-consultorio-profesional',
    legacyModule: 'upss',
    legacyRoute: '/upss/produccioncm',
    workspace: 'main',
    path: 'atencion-ambulatoria-hospitalizacion/consulta-externa-por-por-consultorio-y-profesional',
    label: 'Consulta Externa por por Consultorio y Profesional',
    title: 'Consulta Externa por por Consultorio y Profesional',
    section: 'Departamento Atencion Ambulatoria y Hospitalizacion',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Stethoscope,
  }),
  scaffoldModule({
    key: 'main-consulta-externa-monitoreo',
    legacyModule: 'upss',
    legacyRoute: '/upss/monitoreoce',
    workspace: 'main',
    path: 'atencion-ambulatoria-hospitalizacion/consulta-externa-monitoreo',
    label: 'Consulta Externa - Monitoreo',
    title: 'Consulta Externa - Monitoreo',
    section: 'Departamento Atencion Ambulatoria y Hospitalizacion',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Stethoscope,
  }),
  scaffoldModule({
    key: 'main-consulta-externa-diagnosticos',
    legacyModule: 'upss',
    legacyRoute: '/upss/diagnosticoce',
    workspace: 'main',
    path: 'atencion-ambulatoria-hospitalizacion/consulta-externa-diagnosticos-frecuentes',
    label: 'Consulta Externa - Diagnosticos Frecuentes',
    title: 'Consulta Externa - Diagnosticos Frecuentes',
    section: 'Departamento Atencion Ambulatoria y Hospitalizacion',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Stethoscope,
  }),
  scaffoldModule({
    key: 'main-triaje-admisionados',
    legacyModule: 'otros',
    legacyRoute: '/otros/triajes',
    workspace: 'main',
    path: 'emergencia-cuidados-criticos/triaje-admisionados',
    label: 'Triaje Admisionados',
    title: 'Triaje Admisionados',
    section: 'Departamento Emergencia y Cuidados Criticos',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: ClipboardList,
  }),
  scaffoldModule({
    key: 'main-emergencia',
    legacyModule: 'emergencia',
    legacyRoute: '/emergencia/producciong',
    workspace: 'main',
    path: 'emergencia-cuidados-criticos/emergencia',
    label: 'Emergencia',
    title: 'Emergencia',
    section: 'Departamento Emergencia y Cuidados Criticos',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Ambulance,
  }),
  scaffoldModule({
    key: 'main-emergencia-servicio',
    legacyModule: 'emergencia',
    legacyRoute: '/emergencia/produccion',
    workspace: 'main',
    path: 'emergencia-cuidados-criticos/emergencia-por-servicio',
    label: 'Emergencia por Servicio',
    title: 'Emergencia por Servicio',
    section: 'Departamento Emergencia y Cuidados Criticos',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Ambulance,
  }),
  scaffoldModule({
    key: 'main-indicadores-ucca',
    legacyModule: 'ucca',
    legacyRoute: '/ucca/indicador',
    workspace: 'main',
    path: 'emergencia-cuidados-criticos/indicadores-ucca',
    label: 'Indicadores UCCA (Adulto)',
    title: 'Indicadores UCCA (Adulto)',
    section: 'Departamento Emergencia y Cuidados Criticos',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Activity,
  }),
  scaffoldModule({
    key: 'main-indicadores-uccp',
    legacyModule: 'uccp',
    legacyRoute: '/uccp/indicador',
    workspace: 'main',
    path: 'emergencia-cuidados-criticos/indicadores-uccp',
    label: 'Indicadores UCCP (Pediatrico)',
    title: 'Indicadores UCCP (Pediatrico)',
    section: 'Departamento Emergencia y Cuidados Criticos',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Activity,
  }),
  scaffoldModule({
    key: 'main-centro-quirurgico',
    legacyModule: 'centrocqx',
    legacyRoute: '/centrocqx/produccion',
    workspace: 'main',
    path: 'emergencia-cuidados-criticos/centro-quirurgico',
    label: 'Centro Quirurgico',
    title: 'Centro Quirurgico',
    section: 'Departamento Emergencia y Cuidados Criticos',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Syringe,
  }),
  scaffoldModule({
    key: 'main-imagenologia',
    legacyModule: 'imagenes',
    legacyRoute: '/imagenes/atenciones',
    workspace: 'main',
    path: 'apoyo-diagnostico-tratamiento/imagenologia',
    label: 'Imagenologia',
    title: 'Imagenologia',
    section: 'Departamento Apoyo al Diagnostico y Tratamiento',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Image,
  }),
  scaffoldModule({
    key: 'main-incidentes-eventos-adversos',
    legacyModule: 'calidad',
    legacyRoute: '/calidad/eventos',
    workspace: 'main',
    path: 'unidad-calidad/notificacion-incidentes-eventos-adversos',
    label: 'Notificaci\u00f3n de Incidentes y Eventos Adversos',
    title: 'Notificaci\u00f3n de Incidentes y Eventos Adversos',
    section: 'Unidad de Calidad',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: ShieldPlus,
  }),
  scaffoldModule({
    key: 'main-tamizaje-neonatal',
    legacyModule: 'neonatologia',
    legacyRoute: '/neonatologia/tamizaje',
    workspace: 'main',
    path: 'neonatologia/tamizaje-neonatal-enfermeria',
    label: 'Tamizaje Neonatal - Enfermeria',
    title: 'Tamizaje Neonatal - Enfermeria',
    section: 'Neonatologia',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: HeartPulse,
  }),
  scaffoldModule({
    key: 'main-extraccion-lm',
    legacyModule: 'neonatologia',
    legacyRoute: '/neonatologia/extraccion',
    workspace: 'main',
    path: 'neonatologia/extraccion-lm-enfermeria',
    label: 'Extraccion LM - Enfermeria',
    title: 'Extraccion LM - Enfermeria',
    section: 'Neonatologia',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: HeartPulse,
  }),
  scaffoldModule({
    key: 'main-defunciones',
    legacyModule: 'otros',
    legacyRoute: '/otros/fallecidos',
    workspace: 'main',
    path: 'hechos-vitales/defunciones',
    label: 'Defunciones',
    title: 'Defunciones',
    section: 'Hechos Vitales',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Archive,
  }),
  scaffoldModule({
    key: 'main-inconsistencia-cdef',
    legacyModule: 'otros',
    legacyRoute: '/otros/inconsistencia',
    workspace: 'main',
    path: 'hechos-vitales/inconsistencia-cdef',
    label: 'Inconsistencia CDEF',
    title: 'Inconsistencia CDEF',
    section: 'Hechos Vitales',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Archive,
  }),
  scaffoldModule({
    key: 'main-nacimientos',
    legacyModule: 'otros',
    legacyRoute: '/otros/nacimientos',
    workspace: 'main',
    path: 'hechos-vitales/nacimientos',
    label: 'Nacimientos',
    title: 'Nacimientos',
    section: 'Hechos Vitales',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Archive,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-emergencia',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/emergencia',
    workspace: 'main',
    path: 'sala-inteligente/indicadores-de-emergencia',
    label: 'Indicadores de Emergencia',
    title: 'Indicadores de Emergencia',
    section: 'Sala Inteligente',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-referencia-ce',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/referenciace',
    workspace: 'main',
    path: 'sala-inteligente/referencia-de-consulta-externa',
    label: 'Referencia de Consulta Externa',
    title: 'Referencia de Consulta Externa',
    section: 'Sala Inteligente',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-referencia-emergencia',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/referenciaem',
    workspace: 'main',
    path: 'sala-inteligente/referencia-de-emergencia',
    label: 'Referencia de Emergencia',
    title: 'Referencia de Emergencia',
    section: 'Sala Inteligente',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-interconsulta',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/interconsulta',
    workspace: 'main',
    path: 'sala-inteligente/interconsulta-hospitalaria',
    label: 'Interconsulta Hospitalaria',
    title: 'Interconsulta Hospitalaria',
    section: 'Sala Inteligente',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-enfermeria',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/enfermeria',
    workspace: 'main',
    path: 'sala-inteligente/indicadores-de-enfermeria',
    label: 'Indicadores de Enfermeria',
    title: 'Indicadores de Enfermeria',
    section: 'Sala Inteligente',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-hospitalizados',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/estancia',
    workspace: 'main',
    path: 'sala-inteligente/pacientes-hospitalizados',
    label: 'Pacientes Hospitalizados',
    title: 'Pacientes Hospitalizados',
    section: 'Sala Inteligente',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-continuadores',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/continuador',
    workspace: 'main',
    path: 'sala-inteligente/pacientes-continuadores',
    label: 'Pacientes Continuadores',
    title: 'Pacientes Continuadores',
    section: 'Sala Inteligente',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-isq',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/indicadorisq',
    workspace: 'main',
    path: 'sala-inteligente/indicadores-de-isq-endometritis',
    label: 'Indicadores de ISQ - Endometritis',
    title: 'Indicadores de ISQ - Endometritis',
    section: 'Sala Inteligente',
    patterns: ['filters-chart-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-vacunas',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/inmunizacion',
    workspace: 'main',
    path: 'sala-inteligente/vacunas-enfermeria',
    label: 'Vacunas - Enfermeria',
    title: 'Vacunas - Enfermeria',
    section: 'Sala Inteligente',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-sala-inteligente-iaas',
    legacyModule: 'salamonitoreo',
    legacyRoute: '/salamonitoreo/iass',
    workspace: 'main',
    path: 'sala-inteligente/monitoreo-de-iaas',
    label: 'Monitoreo de IAAS',
    title: 'Monitoreo de IAAS',
    section: 'Sala Inteligente',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: SquareActivity,
  }),
  scaffoldModule({
    key: 'main-reportes-monitoreo',
    legacyModule: 'smental',
    legacyRoute: '/smental/reportes',
    workspace: 'main',
    path: 'monitoreo-salud-mental/reportes-monitoreo',
    label: 'Reportes Monitoreo',
    title: 'Reportes Monitoreo',
    section: 'Monitoreo Salud Mental',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Brain,
  }),
  scaffoldModule({
    key: 'main-tamizaje-salud-mental',
    legacyModule: 'smental',
    legacyRoute: '/smental/tamizajes',
    workspace: 'main',
    path: 'monitoreo-salud-mental/tamizaje-salud-mental',
    label: 'Tamizaje Salud Mental',
    title: 'Tamizaje Salud Mental',
    section: 'Monitoreo Salud Mental',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Brain,
  }),
  scaffoldModule({
    key: 'main-lavado-manos',
    legacyModule: 'epidemiologia',
    legacyRoute: '/epidemiologia/lavado',
    workspace: 'main',
    path: 'epidemiologia/lavado-de-manos',
    label: 'Lavado de Manos',
    title: 'Lavado de Manos',
    section: 'Epidemiologia',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Microscope,
  }),
  scaffoldModule({
    key: 'main-accidente-transito',
    legacyModule: 'epidemiologia',
    legacyRoute: '/epidemiologia/lesionado',
    workspace: 'main',
    path: 'epidemiologia/accidente-de-transito',
    label: 'Accidente de Transito',
    title: 'Accidente de Transito',
    section: 'Epidemiologia',
    patterns: ['filters-table', 'modal-detail'],
    goals: defaultGoals,
    icon: Microscope,
  }),
  scaffoldModule({
    key: 'main-pacientes-oncologicos',
    legacyModule: 'epidemiologia',
    legacyRoute: '/Report/pages/bai_onco.php',
    workspace: 'main',
    path: 'epidemiologia/pacientes-oncologicos',
    label: 'Pacientes Oncologicos',
    title: 'Pacientes Oncologicos',
    section: 'Epidemiologia',
    patterns: ['exporter'],
    goals: defaultGoals,
    icon: Microscope,
  }),
  scaffoldModule({
    key: 'main-pfa-sifilis-sarampion',
    legacyModule: 'epidemiologia',
    legacyRoute: '/Report/pages/enfer.php',
    workspace: 'main',
    path: 'epidemiologia/pfa-sifilis-sarampion',
    label: 'PFA, Sifilis y Sarampion',
    title: 'PFA, Sifilis y Sarampion',
    section: 'Epidemiologia',
    patterns: ['exporter'],
    goals: defaultGoals,
    icon: Microscope,
  }),
  scaffoldModule({
    key: 'main-isqx',
    legacyModule: 'epidemiologia',
    legacyRoute: '/Report/pages/bai_isqx.php',
    workspace: 'main',
    path: 'epidemiologia/isqx',
    label: 'ISQx',
    title: 'ISQx',
    section: 'Epidemiologia',
    patterns: ['exporter'],
    goals: defaultGoals,
    icon: Microscope,
  }),
  scaffoldModule({
    key: 'main-mordedura-canina',
    legacyModule: 'epidemiologia',
    legacyRoute: '/Report/pages/canina.php',
    workspace: 'main',
    path: 'epidemiologia/mordedura-canina',
    label: 'Mordedura Canina',
    title: 'Mordedura Canina',
    section: 'Epidemiologia',
    patterns: ['exporter'],
    goals: defaultGoals,
    icon: Microscope,
  }),
  scaffoldModule({
    key: 'main-cirugia-procedimiento',
    legacyModule: 'epidemiologia',
    legacyRoute: '/Report/pages/CirugiaProc.php',
    workspace: 'main',
    path: 'epidemiologia/cirugia-procedimiento',
    label: 'Cirugia Procedimiento',
    title: 'Cirugia Procedimiento',
    section: 'Epidemiologia',
    patterns: ['exporter'],
    goals: defaultGoals,
    icon: Microscope,
  }),
  scaffoldModule({
    key: 'main-seguimiento-dengue',
    legacyModule: 'epidemiologia',
    legacyRoute: '/Report/pages/otros.php',
    workspace: 'main',
    path: 'epidemiologia/seguimiento-dengue',
    label: 'Seguimiento Dengue',
    title: 'Seguimiento Dengue',
    section: 'Epidemiologia',
    patterns: ['exporter'],
    goals: defaultGoals,
    icon: Microscope,
  }),
] satisfies ModuleDefinition[]

export const sighModules = [] satisfies ModuleDefinition[]

export function getModulesByWorkspace(workspace: WorkspaceKey) {
  return workspace === 'main' ? mainModules : sighModules
}

export function resolveModulePath(module: ModuleDefinition) {
  return `${workspaceMeta[module.workspace].basePath}/${module.path}`
}
