import {
  Activity,
  Ambulance,
  Archive,
  BarChart3,
  BookOpenText,
  Brain,
  ClipboardList,
  FileDown,
  FileText,
  FlaskConical,
  HeartPulse,
  Home,
  Hospital,
  Image,
  Microscope,
  ShieldPlus,
  SquareActivity,
  Stethoscope,
  Syringe,
} from 'lucide-react'
import { group, item, section } from '@/config/navigation-builders'
import type { NavigationSection, WorkspaceHomeContent, WorkspaceQuickLink } from '@/types/navigation'

const homeItem = item({
  key: 'main-home',
  legacyKey: 'inicio',
  legacyRoute: '/inicio',
  label: 'Inicio',
  to: '/app',
  description: 'Entrada principal del Reporteador.',
  icon: Home,
  access: { permissions: ['menu.main.inicio'] },
})

export const mainSections: NavigationSection[] = [
  section({
    key: 'home',
    title: '',
    entries: [homeItem],
  }),
  section({
    key: 'catalog',
    title: '',
    entries: [
      group({
        key: 'main-indicadores-hospitalarios',
        legacyKey: 'indicador',
        label: 'Indicadores Hospitalarios',
        description: 'Indicadores institucionales del menu principal.',
        icon: BarChart3,
        access: { permissions: ['menu.main.indicadores-hospitalarios.*'] },
        items: [
          item({
            key: 'main-indicadores-eficiencia',
            legacyKey: 'eficiencia',
            legacyRoute: '/indicador/eficiencia',
            label: 'Indicadores de Eficiencia',
            to: '/app/indicadores-hospitalarios/indicadores-de-eficiencia',
            description: 'Consulta los indicadores de eficiencia del hospital.',
            icon: BarChart3,
            featured: true,
            access: { permissions: ['menu.main.indicadores-hospitalarios.eficiencia'] },
          }),
          item({
            key: 'main-indicadores-eficacia',
            legacyKey: 'eficacia',
            legacyRoute: '/indicador/eficacia',
            label: 'Indicadores de Eficacia',
            to: '/app/indicadores-hospitalarios/indicadores-de-eficacia',
            description: 'Consulta los indicadores de eficacia del hospital.',
            icon: BarChart3,
            access: { permissions: ['menu.main.indicadores-hospitalarios.eficacia'] },
          }),
          item({
            key: 'main-indicadores-calidad',
            legacyKey: 'calidad',
            legacyRoute: '/indicador/calidad',
            label: 'Indicadores de Calidad',
            to: '/app/indicadores-hospitalarios/indicadores-de-calidad',
            description: 'Consulta los indicadores de calidad del hospital.',
            icon: BarChart3,
            access: { permissions: ['menu.main.indicadores-hospitalarios.calidad'] },
          }),
        ],
      }),
      group({
        key: 'main-atencion-ambulatoria-hospitalizacion',
        legacyKey: 'upss',
        label: 'Departamento Atencion Ambulatoria y Hospitalizacion',
        description: 'Consultas ambulatorias y de hospitalizacion actualmente visibles.',
        icon: Hospital,
        access: { permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.*'] },
        items: [
          item({
            key: 'main-consulta-externa',
            legacyKey: 'producciong',
            legacyRoute: '/upss/producciong',
            label: 'Consulta Externa',
            to: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa',
            description: 'Acceso actual de consulta externa.',
            icon: Stethoscope,
            access: { permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa'] },
          }),
          item({
            key: 'main-consulta-externa-servicio',
            legacyKey: 'produccionec',
            legacyRoute: '/upss/produccionec',
            label: 'Consulta Externa por Servicio',
            to: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-por-servicio',
            description: 'Acceso actual de consulta externa por servicio.',
            icon: Stethoscope,
            access: { permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-por-servicio'] },
          }),
          item({
            key: 'main-consulta-externa-consultorio-profesional',
            legacyKey: 'produccioncm',
            legacyRoute: '/upss/produccioncm',
            label: 'Consulta Externa por por Consultorio y Profesional',
            to: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-por-por-consultorio-y-profesional',
            description: 'Acceso actual por consultorio y profesional.',
            icon: Stethoscope,
            access: {
              permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-por-consultorio-profesional'],
            },
          }),
          item({
            key: 'main-consulta-externa-monitoreo',
            legacyKey: 'monitoreoce',
            legacyRoute: '/upss/monitoreoce',
            label: 'Consulta Externa - Monitoreo',
            to: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-monitoreo',
            description: 'Acceso actual de monitoreo para consulta externa.',
            icon: Stethoscope,
            access: { permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-monitoreo'] },
          }),
          item({
            key: 'main-consulta-externa-diagnosticos',
            legacyKey: 'diagnosticoce',
            legacyRoute: '/upss/diagnosticoce',
            label: 'Consulta Externa - Diagnosticos Frecuentes',
            to: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-diagnosticos-frecuentes',
            description: 'Acceso actual de diagnosticos frecuentes.',
            icon: Stethoscope,
            access: {
              permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-diagnosticos-frecuentes'],
            },
          }),
          item({
            key: 'main-hospitalizacion',
            legacyKey: 'indicadorhosp',
            legacyRoute: '/covid/indicadorhosp',
            label: 'Hospitalizacion',
            to: '/app/atencion-ambulatoria-hospitalizacion/hospitalizacion',
            description: 'Consulta actual de hospitalizacion.',
            icon: Hospital,
            featured: true,
            access: { permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.hospitalizacion'] },
          }),
          item({
            key: 'main-centro-obstetrico',
            legacyKey: 'indicadorobs',
            legacyRoute: '/covid/indicadorobs',
            label: 'Centro Obstetrico',
            to: '/app/atencion-ambulatoria-hospitalizacion/centro-obstetrico',
            description: 'Consulta actual del centro obstetrico.',
            icon: HeartPulse,
            featured: true,
            access: { permissions: ['menu.main.atencion-ambulatoria-hospitalizacion.centro-obstetrico'] },
          }),
        ],
      }),
      group({
        key: 'main-emergencia-cuidados-criticos',
        legacyKey: 'emergencia',
        label: 'Departamento Emergencia y Cuidados Criticos',
        description: 'Consultas del area de emergencia y cuidados criticos.',
        icon: Ambulance,
        access: { permissions: ['menu.main.emergencia-cuidados-criticos.*'] },
        items: [
          item({
            key: 'main-triaje-admisionados',
            legacyKey: 'triajes',
            legacyRoute: '/otros/triajes',
            label: 'Triaje Admisionados',
            to: '/app/emergencia-cuidados-criticos/triaje-admisionados',
            description: 'Acceso actual de triaje admisionados.',
            icon: ClipboardList,
            access: { permissions: ['menu.main.emergencia-cuidados-criticos.triaje-admisionados'] },
          }),
          item({
            key: 'main-emergencia',
            legacyKey: 'producciong',
            legacyRoute: '/emergencia/producciong',
            label: 'Emergencia',
            to: '/app/emergencia-cuidados-criticos/emergencia',
            description: 'Acceso actual de emergencia.',
            icon: Ambulance,
            access: { permissions: ['menu.main.emergencia-cuidados-criticos.emergencia'] },
          }),
          item({
            key: 'main-emergencia-por-servicio',
            legacyKey: 'produccion',
            legacyRoute: '/emergencia/produccion',
            label: 'Emergencia por Servicio',
            to: '/app/emergencia-cuidados-criticos/emergencia-por-servicio',
            description: 'Acceso actual de emergencia por servicio.',
            icon: Ambulance,
            access: { permissions: ['menu.main.emergencia-cuidados-criticos.emergencia-por-servicio'] },
          }),
          item({
            key: 'main-cuidados-criticos',
            legacyKey: 'indicadoruci',
            legacyRoute: '/covid/indicadoruci',
            label: 'Cuidados Criticos UCE Y UCI',
            to: '/app/emergencia-cuidados-criticos/cuidados-criticos-uce-y-uci',
            description: 'Consulta actual de UCE y UCI.',
            icon: Hospital,
            featured: true,
            access: { permissions: ['menu.main.emergencia-cuidados-criticos.cuidados-criticos-uce-y-uci'] },
          }),
          item({
            key: 'main-indicadores-ucca',
            legacyKey: 'indicador',
            legacyRoute: '/ucca/indicador',
            label: 'Indicadores UCCA (Adulto)',
            to: '/app/emergencia-cuidados-criticos/indicadores-ucca',
            description: 'Acceso actual de indicadores UCCA.',
            icon: Activity,
            access: { permissions: ['menu.main.emergencia-cuidados-criticos.indicadores-ucca'] },
          }),
          item({
            key: 'main-indicadores-uccp',
            legacyKey: 'indicador',
            legacyRoute: '/uccp/indicador',
            label: 'Indicadores UCCP (Pediatrico)',
            to: '/app/emergencia-cuidados-criticos/indicadores-uccp',
            description: 'Acceso actual de indicadores UCCP.',
            icon: Activity,
            access: { permissions: ['menu.main.emergencia-cuidados-criticos.indicadores-uccp'] },
          }),
          item({
            key: 'main-centro-quirurgico',
            legacyKey: 'produccion',
            legacyRoute: '/centrocqx/produccion',
            label: 'Centro Quirurgico',
            to: '/app/emergencia-cuidados-criticos/centro-quirurgico',
            description: 'Acceso actual del centro quirurgico.',
            icon: Syringe,
            access: { permissions: ['menu.main.emergencia-cuidados-criticos.centro-quirurgico'] },
          }),
        ],
      }),
      group({
        key: 'main-apoyo-diagnostico-tratamiento',
        legacyKey: 'laboratorio',
        label: 'Departamento Apoyo al Diagnostico y Tratamiento',
        description: 'Consultas de apoyo al diagnostico y tratamiento.',
        icon: FlaskConical,
        access: { permissions: ['menu.main.apoyo-diagnostico-tratamiento.*'] },
        items: [
          item({
            key: 'main-laboratorio',
            legacyKey: 'atenciones',
            legacyRoute: '/laboratorio/atenciones',
            label: 'Laboratorio',
            to: '/app/apoyo-diagnostico-tratamiento/laboratorio',
            description: 'Consulta actual del laboratorio.',
            icon: FlaskConical,
            featured: true,
            access: { permissions: ['menu.main.apoyo-diagnostico-tratamiento.laboratorio'] },
          }),
          item({
            key: 'main-imagenologia',
            legacyKey: 'atenciones',
            legacyRoute: '/imagenes/atenciones',
            label: 'Imagenologia',
            to: '/app/apoyo-diagnostico-tratamiento/imagenologia',
            description: 'Acceso actual de imagenologia.',
            icon: Image,
            access: { permissions: ['menu.main.apoyo-diagnostico-tratamiento.imagenologia'] },
          }),
        ],
      }),
      group({
        key: 'main-unidad-calidad',
        legacyKey: 'calidad',
        label: 'Unidad de Calidad',
        description: 'Consultas visibles de la unidad de calidad.',
        icon: ShieldPlus,
        access: { permissions: ['menu.main.unidad-calidad.*'] },
        items: [
          item({
            key: 'main-incidentes-eventos-adversos',
            legacyKey: 'eventos',
            legacyRoute: '/calidad/eventos',
            label: 'Notificaci\u00f3n de Incidentes y Eventos Adversos',
            to: '/app/unidad-calidad/notificacion-incidentes-eventos-adversos',
            description: 'Acceso actual de incidentes y eventos adversos.',
            icon: ShieldPlus,
            access: { permissions: ['menu.main.unidad-calidad.incidentes-eventos-adversos'] },
          }),
        ],
      }),
      group({
        key: 'main-neonatologia',
        legacyKey: 'neonatologia',
        label: 'Neonatologia',
        description: 'Consultas visibles de neonatologia.',
        icon: HeartPulse,
        access: { permissions: ['menu.main.neonatologia.*'] },
        items: [
          item({
            key: 'main-tamizaje-neonatal',
            legacyKey: 'tamizaje',
            legacyRoute: '/neonatologia/tamizaje',
            label: 'Tamizaje Neonatal - Enfermeria',
            to: '/app/neonatologia/tamizaje-neonatal-enfermeria',
            description: 'Acceso actual de tamizaje neonatal.',
            icon: HeartPulse,
            access: { permissions: ['menu.main.neonatologia.tamizaje-neonatal'] },
          }),
          item({
            key: 'main-extraccion-lm',
            legacyKey: 'extraccion',
            legacyRoute: '/neonatologia/extraccion',
            label: 'Extraccion LM - Enfermeria',
            to: '/app/neonatologia/extraccion-lm-enfermeria',
            description: 'Acceso actual de extraccion LM.',
            icon: HeartPulse,
            access: { permissions: ['menu.main.neonatologia.extraccion-lm'] },
          }),
        ],
      }),
      group({
        key: 'main-hechos-vitales',
        legacyKey: 'otros',
        label: 'Hechos Vitales',
        description: 'Consultas visibles de hechos vitales.',
        icon: Archive,
        access: { permissions: ['menu.main.hechos-vitales.*'] },
        items: [
          item({
            key: 'main-defunciones',
            legacyKey: 'fallecidos',
            legacyRoute: '/otros/fallecidos',
            label: 'Defunciones',
            to: '/app/hechos-vitales/defunciones',
            description: 'Acceso actual de defunciones.',
            icon: Archive,
            access: { permissions: ['menu.main.hechos-vitales.defunciones'] },
          }),
          item({
            key: 'main-inconsistencia-cdef',
            legacyKey: 'inconsistencia',
            legacyRoute: '/otros/inconsistencia',
            label: 'Inconsistencia CDEF',
            to: '/app/hechos-vitales/inconsistencia-cdef',
            description: 'Acceso actual de inconsistencias CDEF.',
            icon: Archive,
            access: { permissions: ['menu.main.hechos-vitales.inconsistencia-cdef'] },
          }),
          item({
            key: 'main-nacimientos',
            legacyKey: 'nacimientos',
            legacyRoute: '/otros/nacimientos',
            label: 'Nacimientos',
            to: '/app/hechos-vitales/nacimientos',
            description: 'Acceso actual de nacimientos.',
            icon: Archive,
            access: { permissions: ['menu.main.hechos-vitales.nacimientos'] },
          }),
        ],
      }),
      group({
        key: 'main-sala-inteligente',
        legacyKey: 'salamonitoreo',
        label: 'Sala Inteligente',
        description: 'Consultas visibles de sala inteligente.',
        icon: SquareActivity,
        access: { permissions: ['menu.main.sala-inteligente.*'] },
        items: [
          item({
            key: 'main-sala-inteligente-emergencia',
            legacyKey: 'emergencia',
            legacyRoute: '/salamonitoreo/emergencia',
            label: 'Indicadores de Emergencia',
            to: '/app/sala-inteligente/indicadores-de-emergencia',
            description: 'Acceso actual de indicadores de emergencia.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.indicadores-de-emergencia'] },
          }),
          item({
            key: 'main-sala-inteligente-referencia-ce',
            legacyKey: 'referenciace',
            legacyRoute: '/salamonitoreo/referenciace',
            label: 'Referencia de Consulta Externa',
            to: '/app/sala-inteligente/referencia-de-consulta-externa',
            description: 'Acceso actual de referencia de consulta externa.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.referencia-de-consulta-externa'] },
          }),
          item({
            key: 'main-sala-inteligente-referencia-emergencia',
            legacyKey: 'referenciaem',
            legacyRoute: '/salamonitoreo/referenciaem',
            label: 'Referencia de Emergencia',
            to: '/app/sala-inteligente/referencia-de-emergencia',
            description: 'Acceso actual de referencia de emergencia.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.referencia-de-emergencia'] },
          }),
          item({
            key: 'main-sala-inteligente-interconsulta',
            legacyKey: 'interconsulta',
            legacyRoute: '/salamonitoreo/interconsulta',
            label: 'Interconsulta Hospitalaria',
            to: '/app/sala-inteligente/interconsulta-hospitalaria',
            description: 'Acceso actual de interconsulta hospitalaria.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.interconsulta-hospitalaria'] },
          }),
          item({
            key: 'main-sala-inteligente-enfermeria',
            legacyKey: 'enfermeria',
            legacyRoute: '/salamonitoreo/enfermeria',
            label: 'Indicadores de Enfermeria',
            to: '/app/sala-inteligente/indicadores-de-enfermeria',
            description: 'Acceso actual de indicadores de enfermeria.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.indicadores-de-enfermeria'] },
          }),
          item({
            key: 'main-sala-inteligente-pacientes-hospitalizados',
            legacyKey: 'estancia',
            legacyRoute: '/salamonitoreo/estancia',
            label: 'Pacientes Hospitalizados',
            to: '/app/sala-inteligente/pacientes-hospitalizados',
            description: 'Acceso actual de pacientes hospitalizados.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.pacientes-hospitalizados'] },
          }),
          item({
            key: 'main-sala-inteligente-continuadores',
            legacyKey: 'continuador',
            legacyRoute: '/salamonitoreo/continuador',
            label: 'Pacientes Continuadores',
            to: '/app/sala-inteligente/pacientes-continuadores',
            description: 'Acceso actual de pacientes continuadores.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.pacientes-continuadores'] },
          }),
          item({
            key: 'main-sala-inteligente-isq',
            legacyKey: 'indicadorisq',
            legacyRoute: '/salamonitoreo/indicadorisq',
            label: 'Indicadores de ISQ - Endometritis',
            to: '/app/sala-inteligente/indicadores-de-isq-endometritis',
            description: 'Acceso actual de indicadores ISQ.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.indicadores-de-isq-endometritis'] },
          }),
          item({
            key: 'main-sala-inteligente-vacunas',
            legacyKey: 'inmunizacion',
            legacyRoute: '/salamonitoreo/inmunizacion',
            label: 'Vacunas - Enfermeria',
            to: '/app/sala-inteligente/vacunas-enfermeria',
            description: 'Acceso actual de vacunas de enfermeria.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.vacunas-enfermeria'] },
          }),
          item({
            key: 'main-sala-inteligente-iaas',
            legacyKey: 'iass',
            legacyRoute: '/salamonitoreo/iass',
            label: 'Monitoreo de IAAS',
            to: '/app/sala-inteligente/monitoreo-de-iaas',
            description: 'Acceso actual de monitoreo de IAAS.',
            icon: SquareActivity,
            access: { permissions: ['menu.main.sala-inteligente.monitoreo-de-iaas'] },
          }),
        ],
      }),
      group({
        key: 'main-monitoreo-salud-mental',
        legacyKey: 'smental',
        label: 'Monitoreo Salud Mental',
        description: 'Consultas visibles de salud mental.',
        icon: Brain,
        access: { permissions: ['menu.main.monitoreo-salud-mental.*'] },
        items: [
          item({
            key: 'main-reportes-monitoreo',
            legacyKey: 'reportes',
            legacyRoute: '/smental/reportes',
            label: 'Reportes Monitoreo',
            to: '/app/monitoreo-salud-mental/reportes-monitoreo',
            description: 'Acceso actual de reportes de salud mental.',
            icon: Brain,
            access: { permissions: ['menu.main.monitoreo-salud-mental.reportes-monitoreo'] },
          }),
          item({
            key: 'main-tamizaje-salud-mental',
            legacyKey: 'tamizajes',
            legacyRoute: '/smental/tamizajes',
            label: 'Tamizaje Salud Mental',
            to: '/app/monitoreo-salud-mental/tamizaje-salud-mental',
            description: 'Acceso actual de tamizaje de salud mental.',
            icon: Brain,
            access: { permissions: ['menu.main.monitoreo-salud-mental.tamizaje-salud-mental'] },
          }),
        ],
      }),
      group({
        key: 'main-zona-descarga',
        legacyKey: 'exportadato',
        label: 'Zona de Descarga',
        description: 'Descargas actuales del menu principal.',
        icon: FileDown,
        access: { permissions: ['menu.main.zona-descarga.*'] },
        items: [
          item({
            key: 'main-registros-procesados',
            legacyKey: 'exportadata',
            legacyRoute: '/exportadato/exportadata',
            label: 'Registros Procesados',
            to: '/app/zona-descarga/registros-procesados',
            description: 'Consulta y descarga registros procesados.',
            icon: FileDown,
            featured: true,
            access: { permissions: ['menu.main.zona-descarga.registros-procesados'] },
          }),
        ],
      }),
      group({
        key: 'main-articulacion-prestacional',
        legacyKey: 'admision',
        label: 'Departamento de Articulacion Prestacional',
        description: 'Consultas visibles de articulacion prestacional.',
        icon: ClipboardList,
        access: { permissions: ['menu.main.articulacion-prestacional.*'] },
        items: [
          item({
            key: 'main-monitoreo-citas',
            legacyKey: 'monitoreo',
            legacyRoute: '/admision/monitoreo',
            label: 'Monitoreo de Citas',
            to: '/app/articulacion-prestacional/monitoreo-de-citas',
            description: 'Seguimiento actual del monitoreo de citas.',
            icon: ClipboardList,
            featured: true,
            access: { permissions: ['menu.main.articulacion-prestacional.monitoreo-de-citas'] },
          }),
          item({
            key: 'main-citas-reprogramadas',
            legacyKey: 'citasrpg',
            legacyRoute: '/admision/citasrpg',
            label: 'Indicador Citas Reprogramdas',
            to: '/app/articulacion-prestacional/indicador-citas-reprogramdas',
            description: 'Consulta actual del indicador de citas reprogramadas.',
            icon: ClipboardList,
            access: { permissions: ['menu.main.articulacion-prestacional.indicador-citas-reprogramdas'] },
          }),
        ],
      }),
      group({
        key: 'main-epidemiologia',
        legacyKey: 'epidemiologia',
        label: 'Epidemiologia',
        description: 'Consultas visibles de epidemiologia.',
        icon: Microscope,
        access: { permissions: ['menu.main.epidemiologia.*'] },
        items: [
          item({
            key: 'main-lavado-manos',
            legacyKey: 'lavado',
            legacyRoute: '/epidemiologia/lavado',
            label: 'Lavado de Manos',
            to: '/app/epidemiologia/lavado-de-manos',
            description: 'Acceso actual de lavado de manos.',
            icon: Microscope,
            access: { permissions: ['menu.main.epidemiologia.lavado-de-manos'] },
          }),
          item({
            key: 'main-accidente-transito',
            legacyKey: 'lesionado',
            legacyRoute: '/epidemiologia/lesionado',
            label: 'Accidente de Transito',
            to: '/app/epidemiologia/accidente-de-transito',
            description: 'Acceso actual de accidente de transito.',
            icon: Microscope,
            access: { permissions: ['menu.main.epidemiologia.accidente-de-transito'] },
          }),
        ],
      }),
    ],
  }),
]

export const mainQuickLinks: WorkspaceQuickLink[] = [
  {
    key: 'manuales',
    label: 'Ver manuales y tutoriales',
    href: 'https://recursos.heves.gob.pe/',
    description: 'Abre la biblioteca institucional de apoyo al usuario.',
    icon: BookOpenText,
    external: true,
  },
  {
    key: 'formulario',
    label: 'Formulario de solicitud de informacion',
    href: 'https://docs.google.com/forms/d/e/1FAIpQLSe2MFZojk3J2nIPS_UCGmDIHjID3s1qwDb9OYEvG6XwG2fKew/viewform',
    description: 'Permite registrar nuevas solicitudes de informacion.',
    icon: FileText,
    external: true,
  },
  {
    key: 'desembalse',
    label: 'Desembalse Quirurgico 2024',
    href: 'https://app.powerbi.com/view?r=eyJrIjoiNDFlMTdmNGQtMWM3MC00NTI3LWFjYmEtNWU2NjBhMTk0NjVmIiwidCI6ImIwZDQ1ZmViLTM5MzUtNGE4ZS04YTc1LTNhYWM4MGQ4NTMzYSJ9',
    description: 'Acceso historico al tablero institucional.',
    icon: Activity,
    external: true,
  },
  {
    key: 'operacion-vida',
    label: 'Operacion VIDA',
    href: 'https://app.powerbi.com/view?r=eyJrIjoiZDQ2Y2ZmNTktMzY4Ny00NzQxLTk3OTgtOWRhYmQyY2RmYzU2IiwidCI6ImIwZDQ1ZmViLTM5MzUtNGE4ZS04YTc1LTNhYWM4MGQ4NTMzYSJ9',
    description: 'Acceso historico al tablero institucional.',
    icon: Activity,
    external: true,
  },
]

export const mainHomeContent: WorkspaceHomeContent = {
  title: 'Inicio',
  description: 'Revise los accesos visibles del Principal y entre directo a los submenus de uso frecuente.',
  featuredTitle: 'Accesos frecuentes',
  featuredDescription: 'Consultas destacadas dentro del menu real actual del Principal.',
  supportTitle: 'Menu actual del Principal',
  supportDescription: 'La taxonomia, el orden y los nombres siguen la navegacion real del Reporteador legacy.',
}
