export type CatalogWorkspace = 'principal' | 'datos-en-linea'
export type CatalogResourceType = 'exportable' | 'vista' | 'tablero' | 'monitoreo' | 'reporte'

export interface CatalogResource {
  id: string
  title: string
  description: string
  workspace: CatalogWorkspace
  workspaceLabel: string
  type: CatalogResourceType
  category: string
  subcategory?: string
  route: string
  breadcrumb: string
  legacyName?: string
  aliases: string[]
  keywords: string[]
  summary?: string
  questions?: string[]
  mainIndicators?: string[]
  filters?: string[]
  targetUsers?: string[]
  useCases?: string[]
  permissionKey?: string
  featured?: boolean
}

type CatalogResourceEnhancement = Partial<
  Pick<
    CatalogResource,
    | 'title'
    | 'description'
    | 'category'
    | 'breadcrumb'
    | 'legacyName'
    | 'aliases'
    | 'keywords'
    | 'summary'
    | 'questions'
    | 'mainIndicators'
    | 'filters'
    | 'targetUsers'
    | 'useCases'
    | 'featured'
  >
>

const navigationCatalogBase: CatalogResource[] = [
  // ── PRINCIPAL / REPORTEADOR ──────────────────────────────────────────────

  // Indicadores Hospitalarios
  {
    id: 'main-indicadores-eficiencia',
    title: 'Indicadores de Eficiencia',
    description: 'Tablero institucional de indicadores de eficiencia hospitalaria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Indicadores Hospitalarios',
    route: '/app/indicadores-hospitalarios/indicadores-de-eficiencia',
    breadcrumb: 'Reporteador → Indicadores Hospitalarios',
    aliases: ['indicadores', 'eficiencia', 'kpi'],
    keywords: ['indicador', 'eficiencia', 'hospitalario', 'tablero', 'powerbi'],
    permissionKey: 'menu.main.indicadores-hospitalarios.eficiencia',
    featured: true,
  },
  {
    id: 'main-indicadores-eficacia',
    title: 'Indicadores de Eficacia',
    description: 'Tablero institucional de indicadores de eficacia hospitalaria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Indicadores Hospitalarios',
    route: '/app/indicadores-hospitalarios/indicadores-de-eficacia',
    breadcrumb: 'Reporteador → Indicadores Hospitalarios',
    aliases: ['indicadores', 'eficacia', 'kpi'],
    keywords: ['indicador', 'eficacia', 'hospitalario', 'tablero'],
    permissionKey: 'menu.main.indicadores-hospitalarios.eficacia',
  },
  {
    id: 'main-indicadores-calidad',
    title: 'Indicadores de Calidad',
    description: 'Tablero institucional de indicadores de calidad hospitalaria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Indicadores Hospitalarios',
    route: '/app/indicadores-hospitalarios/indicadores-de-calidad',
    breadcrumb: 'Reporteador → Indicadores Hospitalarios',
    aliases: ['indicadores', 'calidad', 'kpi'],
    keywords: ['indicador', 'calidad', 'hospitalario', 'tablero'],
    permissionKey: 'menu.main.indicadores-hospitalarios.calidad',
  },

  // Atención Ambulatoria y Hospitalización
  {
    id: 'main-consulta-externa',
    title: 'Consulta Externa',
    description: 'Producción y monitoreo de consulta externa ambulatoria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['ambulatoria', 'ce', 'consultorios'],
    keywords: ['consulta', 'externa', 'ambulatoria', 'produccion', 'citas'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa',
  },
  {
    id: 'main-consulta-externa-servicio',
    title: 'Consulta Externa por Servicio',
    description: 'Producción de consulta externa desagregada por servicio.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-por-servicio',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['consulta externa servicio', 'ce servicio'],
    keywords: ['consulta', 'externa', 'servicio', 'especialidad', 'produccion'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-por-servicio',
  },
  {
    id: 'main-consulta-externa-consultorio-profesional',
    title: 'Consulta Externa por Consultorio y Profesional',
    description: 'Vista de producción por consultorio y profesional de salud.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'vista',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-por-por-consultorio-y-profesional',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['consultorio profesional', 'medico consultorio'],
    keywords: ['consulta', 'externa', 'consultorio', 'profesional', 'medico'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-por-consultorio-profesional',
  },
  {
    id: 'main-consulta-externa-monitoreo',
    title: 'Consulta Externa — Monitoreo',
    description: 'Monitoreo en tiempo real de la consulta externa.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-monitoreo',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['monitoreo ce', 'seguimiento consulta'],
    keywords: ['monitoreo', 'consulta', 'externa', 'tiempo real'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-monitoreo',
  },
  {
    id: 'main-consulta-externa-diagnosticos',
    title: 'Consulta Externa — Diagnósticos Frecuentes',
    description: 'Diagnósticos más frecuentes en consulta externa.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-diagnosticos-frecuentes',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['diagnosticos frecuentes', 'cie10', 'morbilidad ambulatoria'],
    keywords: ['diagnostico', 'frecuente', 'consulta', 'externa', 'cie'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-diagnosticos-frecuentes',
  },
  {
    id: 'main-hospitalizacion',
    title: 'Hospitalización',
    description: 'Indicadores de hospitalización: ocupación, estancia y producción.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/hospitalizacion',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['hospitalizados', 'internados', 'camas hospitalización', 'pacientes internados'],
    keywords: ['hospitalizacion', 'hospitalizados', 'internados', 'cama', 'estancia', 'ocupacion'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.hospitalizacion',
    featured: true,
  },
  {
    id: 'main-centro-obstetrico',
    title: 'Centro Obstétrico',
    description: 'Indicadores obstétricos: partos, cesáreas y morbilidad materna.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/centro-obstetrico',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['obstetrico', 'partos', 'cesarea', 'maternidad', 'morbilidad materna', 'bai', 'BAI morbilidad materna extrema'],
    keywords: ['obstetrico', 'parto', 'cesarea', 'maternidad', 'morbilidad', 'materna', 'BAI', 'bai'],
    legacyName: 'BAI - Morbilidad Materna Extrema',
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.centro-obstetrico',
    featured: true,
  },

  // Emergencia y Cuidados Críticos
  {
    id: 'main-triaje-admisionados',
    title: 'Triaje Admisionados',
    description: 'Listado nominal de ingresos nuevos en servicios de emergencia.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/triaje-admisionados',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    legacyName: 'Listado Nominal de Ingresos Nuevos en los Servicios de Emergencia',
    aliases: ['admisionados emergencia', 'ingresos emergencia', 'triaje', 'admitidos'],
    keywords: ['triaje', 'admisionado', 'ingreso', 'emergencia', 'listado', 'nominal'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.triaje-admisionados',
  },
  {
    id: 'main-emergencia',
    title: 'Emergencia',
    description: 'Producción general del servicio de emergencia.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/emergencia',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['urgencias', 'emergencias'],
    keywords: ['emergencia', 'urgencia', 'produccion'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.emergencia',
  },
  {
    id: 'main-emergencia-por-servicio',
    title: 'Emergencia por Servicio',
    description: 'Producción del servicio de emergencia por especialidad.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/emergencia-por-servicio',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['emergencia servicio', 'urgencias especialidad'],
    keywords: ['emergencia', 'servicio', 'especialidad', 'produccion'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.emergencia-por-servicio',
  },
  {
    id: 'main-cuidados-criticos',
    title: 'Cuidados Críticos UCE y UCI',
    description: 'Indicadores de Unidad de Cuidados Críticos (UCE adulto y UCI).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/cuidados-criticos-uce-y-uci',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['uci', 'uce', 'unidad cuidados intensivos', 'criticos'],
    keywords: ['cuidados', 'criticos', 'uci', 'uce', 'intensivos'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.cuidados-criticos-uce-y-uci',
    featured: true,
  },
  {
    id: 'main-indicadores-ucca',
    title: 'Indicadores UCCA (Adulto)',
    description: 'Indicadores de la Unidad de Cuidados Críticos Adulto.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/indicadores-ucca',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['ucca', 'cuidados criticos adulto'],
    keywords: ['ucca', 'adulto', 'cuidados', 'criticos', 'indicadores'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.indicadores-ucca',
  },
  {
    id: 'main-indicadores-uccp',
    title: 'Indicadores UCCP (Pediátrico)',
    description: 'Indicadores de la Unidad de Cuidados Críticos Pediátrico.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/indicadores-uccp',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['uccp', 'cuidados criticos pediatrico', 'pediatrico critico'],
    keywords: ['uccp', 'pediatrico', 'cuidados', 'criticos', 'indicadores'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.indicadores-uccp',
  },
  {
    id: 'main-centro-quirurgico',
    title: 'Centro Quirúrgico',
    description: 'Producción del centro quirúrgico: cirugías y procedimientos.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/centro-quirurgico',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['quirurgico', 'cirugias', 'sala de operaciones', 'sop'],
    keywords: ['quirurgico', 'cirugia', 'operaciones', 'produccion', 'sala'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.centro-quirurgico',
  },

  // Apoyo al Diagnóstico y Tratamiento
  {
    id: 'main-laboratorio',
    title: 'Laboratorio',
    description: 'Producción del laboratorio clínico.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Apoyo al Diagnóstico y Tratamiento',
    route: '/app/apoyo-diagnostico-tratamiento/laboratorio',
    breadcrumb: 'Reporteador → Apoyo al Diagnóstico y Tratamiento',
    aliases: ['lab', 'analisis clinico', 'laboratorio clinico'],
    keywords: ['laboratorio', 'analisis', 'clinico', 'muestra', 'resultado'],
    permissionKey: 'menu.main.apoyo-diagnostico-tratamiento.laboratorio',
    featured: true,
  },
  {
    id: 'main-imagenologia',
    title: 'Imagenología',
    description: 'Producción del servicio de imagenología: rayos X, ecografías, etc.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Apoyo al Diagnóstico y Tratamiento',
    route: '/app/apoyo-diagnostico-tratamiento/imagenologia',
    breadcrumb: 'Reporteador → Apoyo al Diagnóstico y Tratamiento',
    aliases: ['imagenes', 'rayos x', 'ecografia', 'radiologia'],
    keywords: ['imagenologia', 'rayos', 'ecografia', 'radiologia', 'imagen'],
    permissionKey: 'menu.main.apoyo-diagnostico-tratamiento.imagenologia',
  },

  // Unidad de Calidad
  {
    id: 'main-incidentes-eventos-adversos',
    title: 'Notificación de Incidentes y Eventos Adversos',
    description: 'Registro y seguimiento de incidentes clínicos y eventos adversos.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Unidad de Calidad',
    route: '/app/unidad-calidad/notificacion-incidentes-eventos-adversos',
    breadcrumb: 'Reporteador → Unidad de Calidad',
    aliases: ['eventos adversos', 'incidentes', 'calidad', 'seguridad paciente'],
    keywords: ['incidente', 'evento', 'adverso', 'calidad', 'seguridad', 'notificacion'],
    permissionKey: 'menu.main.unidad-calidad.incidentes-eventos-adversos',
  },

  // Neonatología
  {
    id: 'main-tamizaje-neonatal',
    title: 'Tamizaje Neonatal — Enfermería',
    description: 'Registro de tamizaje neonatal realizado por enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Neonatología',
    route: '/app/neonatologia/tamizaje-neonatal-enfermeria',
    breadcrumb: 'Reporteador → Neonatología',
    aliases: ['neonato', 'tamizaje neonatal', 'recien nacido'],
    keywords: ['tamizaje', 'neonatal', 'enfermeria', 'neonato', 'nacido'],
    permissionKey: 'menu.main.neonatologia.tamizaje-neonatal',
  },
  {
    id: 'main-extraccion-lm',
    title: 'Extracción LM — Enfermería',
    description: 'Registro de extracción de leche materna por enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Neonatología',
    route: '/app/neonatologia/extraccion-lm-enfermeria',
    breadcrumb: 'Reporteador → Neonatología',
    aliases: ['lactancia materna', 'leche materna', 'extraccion lm'],
    keywords: ['extraccion', 'leche', 'materna', 'lactancia', 'neonato', 'enfermeria'],
    permissionKey: 'menu.main.neonatologia.extraccion-lm',
  },

  // Hechos Vitales
  {
    id: 'main-defunciones',
    title: 'Defunciones',
    description: 'Tablero de hechos vitales: defunciones y fallecidos.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Hechos Vitales',
    route: '/app/hechos-vitales/defunciones',
    breadcrumb: 'Reporteador → Hechos Vitales',
    aliases: ['fallecidos', 'muertes', 'defunciones', 'obituario', 'reporte diario fallecidos'],
    keywords: ['defuncion', 'fallecido', 'muerte', 'vital', 'obituario'],
    permissionKey: 'menu.main.hechos-vitales.defunciones',
    featured: true,
  },
  {
    id: 'main-inconsistencia-cdef',
    title: 'Inconsistencia CDEF',
    description: 'Inconsistencias en registros de certificados de defunción (CDEF).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Hechos Vitales',
    route: '/app/hechos-vitales/inconsistencia-cdef',
    breadcrumb: 'Reporteador → Hechos Vitales',
    aliases: ['cdef', 'certificado defuncion', 'inconsistencias'],
    keywords: ['cdef', 'certificado', 'defuncion', 'inconsistencia'],
    permissionKey: 'menu.main.hechos-vitales.inconsistencia-cdef',
  },
  {
    id: 'main-nacimientos',
    title: 'Nacimientos',
    description: 'Registro y estadísticas de nacimientos institucionales.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Hechos Vitales',
    route: '/app/hechos-vitales/nacimientos',
    breadcrumb: 'Reporteador → Hechos Vitales',
    aliases: ['partos', 'nacidos', 'nuevos nacimientos'],
    keywords: ['nacimiento', 'parto', 'nacido', 'vital'],
    permissionKey: 'menu.main.hechos-vitales.nacimientos',
  },

  // Sala Inteligente
  {
    id: 'main-sala-inteligente-emergencia',
    title: 'Indicadores de Emergencia',
    description: 'Indicadores en tiempo real del servicio de emergencia (Sala Inteligente).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/indicadores-de-emergencia',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['sala inteligente emergencia', 'monitoreo emergencia'],
    keywords: ['sala', 'inteligente', 'indicadores', 'emergencia', 'monitoreo'],
    permissionKey: 'menu.main.sala-inteligente.indicadores-de-emergencia',
  },
  {
    id: 'main-sala-inteligente-referencia-ce',
    title: 'Referencia de Consulta Externa',
    description: 'Seguimiento de referencias y contrarreferencias de consulta externa.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/referencia-de-consulta-externa',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['referencias ce', 'contrarreferencias consulta', 'referencia ambulatoria'],
    keywords: ['referencia', 'contrarreferencia', 'consulta', 'externa'],
    permissionKey: 'menu.main.sala-inteligente.referencia-de-consulta-externa',
  },
  {
    id: 'main-sala-inteligente-referencia-emergencia',
    title: 'Referencia de Emergencia',
    description: 'Seguimiento de referencias y contrarreferencias de emergencia.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/referencia-de-emergencia',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['referencias emergencia', 'contrarreferencias urgencias'],
    keywords: ['referencia', 'contrarreferencia', 'emergencia', 'urgencia'],
    permissionKey: 'menu.main.sala-inteligente.referencia-de-emergencia',
  },
  {
    id: 'main-sala-inteligente-interconsulta',
    title: 'Interconsulta Hospitalaria',
    description: 'Monitoreo de interconsultas entre servicios hospitalarios.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/interconsulta-hospitalaria',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['interconsulta', 'interconsultas', 'consulta entre servicios'],
    keywords: ['interconsulta', 'hospitalaria', 'servicio', 'consulta'],
    permissionKey: 'menu.main.sala-inteligente.interconsulta-hospitalaria',
  },
  {
    id: 'main-sala-inteligente-enfermeria',
    title: 'Indicadores de Enfermería',
    description: 'Indicadores de desempeño del servicio de enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/indicadores-de-enfermeria',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['enfermeria', 'indicadores enfermeria'],
    keywords: ['enfermeria', 'indicadores', 'sala', 'inteligente'],
    permissionKey: 'menu.main.sala-inteligente.indicadores-de-enfermeria',
  },
  {
    id: 'main-sala-inteligente-isq',
    title: 'Indicadores de ISQ — Endometritis',
    description: 'Indicadores de infección de sitio quirúrgico y endometritis.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/indicadores-de-isq-endometritis',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['isq', 'endometritis', 'infeccion quirurgica', 'infeccion sitio quirurgico'],
    keywords: ['isq', 'endometritis', 'infeccion', 'quirurgico', 'indicadores'],
    permissionKey: 'menu.main.sala-inteligente.indicadores-de-isq-endometritis',
  },
  {
    id: 'main-sala-inteligente-vacunas',
    title: 'Vacunas — Enfermería',
    description: 'Registro de aplicación de vacunas por el servicio de enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/vacunas-enfermeria',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['vacunas', 'inmunizacion', 'vacunacion'],
    keywords: ['vacuna', 'inmunizacion', 'vacunacion', 'enfermeria'],
    permissionKey: 'menu.main.sala-inteligente.vacunas-enfermeria',
  },
  {
    id: 'main-sala-inteligente-iaas',
    title: 'Monitoreo de IAAS',
    description: 'Monitoreo de Infecciones Asociadas a la Atención en Salud (IAAS).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/monitoreo-de-iaas',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['iaas', 'infecciones hospitalarias', 'nosocomiales', 'iras nosocomiales'],
    keywords: ['iaas', 'infeccion', 'hospitalaria', 'nosocomial', 'atencion', 'salud', 'monitoreo'],
    permissionKey: 'menu.main.sala-inteligente.monitoreo-de-iaas',
  },

  // Monitoreo Salud Mental
  {
    id: 'main-salud-mental-reportes',
    title: 'Reportes Monitoreo — Salud Mental',
    description: 'Reportes de monitoreo en salud mental: violencia, ansiedad, depresión, etc.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Monitoreo Salud Mental',
    route: '/app/monitoreo-salud-mental/reportes-monitoreo',
    breadcrumb: 'Reporteador → Monitoreo Salud Mental',
    aliases: ['salud mental', 'psiquiatria', 'psicologia', 'violencia', 'ansiedad', 'depresion', 'conducta', 'mental'],
    keywords: ['salud', 'mental', 'reporte', 'monitoreo', 'violencia', 'ansiedad', 'depresion', 'psiquiatria', 'psicologia'],
    permissionKey: 'menu.main.monitoreo-salud-mental.reportes-monitoreo',
    featured: true,
  },
  {
    id: 'main-tamizaje-salud-mental',
    title: 'Tamizaje Salud Mental',
    description: 'Tamizaje de salud mental: PHQ-9, GAD-7 y otras escalas.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Monitoreo Salud Mental',
    route: '/app/monitoreo-salud-mental/tamizaje-salud-mental',
    breadcrumb: 'Reporteador → Monitoreo Salud Mental',
    aliases: ['tamizaje mental', 'phq', 'gad', 'cribado mental', 'salud mental tamizaje'],
    keywords: ['tamizaje', 'salud', 'mental', 'phq', 'gad', 'escala', 'cribado'],
    permissionKey: 'menu.main.monitoreo-salud-mental.tamizaje-salud-mental',
  },

  // Zona de Descarga / Exportar Datos
  {
    id: 'main-registros-procesados',
    title: 'Exportar Datos — Registros Procesados',
    description: 'Exportación de datos institucionales incluyendo BAI - Morbilidad Materna Extrema y otros registros procesados.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Zona de Descarga',
    route: '/app/zona-descarga/registros-procesados',
    breadcrumb: 'Reporteador → Zona de Descarga',
    legacyName: 'Exportar Datos / BAI - Morbilidad Materna Extrema',
    aliases: ['exportar datos', 'registros', 'descarga', 'bai', 'morbilidad materna', 'dengue sin signos de alarma', 'a97.0', 'sisgalenplus', 'exportar registros procesados'],
    keywords: ['exportar', 'datos', 'registro', 'descarga', 'bai', 'morbilidad', 'materna', 'dengue', 'a97.0', 'sisgalenplus', 'procesado'],
    permissionKey: 'menu.main.zona-descarga.registros-procesados',
    featured: true,
  },

  // Articulación Prestacional
  {
    id: 'main-monitoreo-citas',
    title: 'Monitoreo de Citas',
    description: 'Monitoreo de la programación y asignación de citas médicas.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Articulación Prestacional',
    route: '/app/articulacion-prestacional/monitoreo-de-citas',
    breadcrumb: 'Reporteador → Articulación Prestacional',
    aliases: ['citas medicas', 'agenda medica', 'programacion citas'],
    keywords: ['cita', 'medica', 'programacion', 'monitoreo', 'agenda'],
    permissionKey: 'menu.main.articulacion-prestacional.monitoreo-de-citas',
    featured: true,
  },
  {
    id: 'main-citas-reprogramadas',
    title: 'Indicador Citas Reprogramadas',
    description: 'Indicador de citas reprogramadas para seguimiento de demanda.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Articulación Prestacional',
    route: '/app/articulacion-prestacional/indicador-citas-reprogramdas',
    breadcrumb: 'Reporteador → Articulación Prestacional',
    aliases: ['citas reprogramadas', 'reprogramadas', 'indicador citas'],
    keywords: ['cita', 'reprogramada', 'indicador', 'demanda'],
    permissionKey: 'menu.main.articulacion-prestacional.indicador-citas-reprogramdas',
  },

  // Epidemiología
  {
    id: 'main-lavado-manos',
    title: 'Lavado de Manos',
    description: 'Exportación de registros de lavado de manos para vigilancia epidemiológica.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiología',
    route: '/app/epidemiologia/lavado-de-manos',
    breadcrumb: 'Reporteador → Epidemiología',
    legacyName: 'Registro de Lavado de Manos — Exportar',
    aliases: ['lavado manos', 'higiene manos', 'epidemiologia lavado', 'registro lavado'],
    keywords: ['lavado', 'manos', 'higiene', 'epidemiologia', 'registro', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.lavado-de-manos',
    featured: true,
  },
  {
    id: 'main-accidente-transito',
    title: 'Accidente de Tránsito',
    description: 'Registro epidemiológico de pacientes lesionados en accidentes de tránsito.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Epidemiología',
    route: '/app/epidemiologia/accidente-de-transito',
    breadcrumb: 'Reporteador → Epidemiología',
    aliases: ['accidente transito', 'lesionados', 'accidentados'],
    keywords: ['accidente', 'transito', 'lesionado', 'epidemiologia'],
    permissionKey: 'menu.main.epidemiologia.accidente-de-transito',
  },
  {
    id: 'main-pacientes-oncologicos',
    title: 'Pacientes Oncologicos',
    description: 'Exportacion de pacientes con diagnostico oncologico desde el reporte legacy de UIS.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiologia',
    route: '/app/epidemiologia/pacientes-oncologicos',
    breadcrumb: 'Reporteador -> Epidemiologia',
    legacyName: 'Busqueda de Pacientes Oncologicos',
    aliases: ['oncologicos', 'bai onco', 'pacientes cancer', 'oncologia'],
    keywords: ['oncologico', 'oncologia', 'bai', 'epidemiologia', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.pacientes-oncologicos',
    featured: true,
  },
  {
    id: 'main-pfa-sifilis-sarampion',
    title: 'PFA, Sifilis y Sarampion',
    description: 'Exportacion de PFA, sifilis, sarampion, rubeola y SRC.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiologia',
    route: '/app/epidemiologia/pfa-sifilis-sarampion',
    breadcrumb: 'Reporteador -> Epidemiologia',
    legacyName: 'PFA/Sifilis/Sarampion',
    aliases: ['pfa', 'sifilis', 'sarampion', 'rubeola', 'src'],
    keywords: ['pfa', 'sifilis', 'sarampion', 'rubeola', 'src', 'epidemiologia', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.pfa-sifilis-sarampion',
    featured: true,
  },
  {
    id: 'main-isqx',
    title: 'ISQx',
    description: 'Monitoreo y exportacion de infeccion del sitio quirurgico.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiologia',
    route: '/app/epidemiologia/isqx',
    breadcrumb: 'Reporteador -> Epidemiologia',
    legacyName: 'ISQx',
    aliases: ['bai isqx', 'isq', 'infeccion sitio quirurgico'],
    keywords: ['isqx', 'isq', 'infeccion', 'quirurgico', 'epidemiologia', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.isqx',
    featured: true,
  },
  {
    id: 'main-mordedura-canina',
    title: 'Mordedura Canina',
    description: 'Exportacion de pacientes con diagnosticos relacionados a mordedura canina.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiologia',
    route: '/app/epidemiologia/mordedura-canina',
    breadcrumb: 'Reporteador -> Epidemiologia',
    legacyName: 'Mordedura canina',
    aliases: ['mordedura canina', 'canina', 'rabia'],
    keywords: ['mordedura', 'canina', 'rabia', 'epidemiologia', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.mordedura-canina',
    featured: true,
  },
  {
    id: 'main-cirugia-procedimiento',
    title: 'Cirugia Procedimiento',
    description: 'Exportacion de procedimientos quirurgicos por periodo.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiologia',
    route: '/app/epidemiologia/cirugia-procedimiento',
    breadcrumb: 'Reporteador -> Epidemiologia',
    legacyName: 'Cirugia Procedimiento',
    aliases: ['cirugia procedimiento', 'procedimientos quirurgicos'],
    keywords: ['cirugia', 'procedimiento', 'quirurgico', 'epidemiologia', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.cirugia-procedimiento',
    featured: true,
  },
  {
    id: 'main-seguimiento-dengue',
    title: 'Seguimiento Dengue',
    description: 'Exportacion de pacientes hospitalizados con dengue.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiologia',
    route: '/app/epidemiologia/seguimiento-dengue',
    breadcrumb: 'Reporteador -> Epidemiologia',
    legacyName: 'Seguimiento dengue',
    aliases: ['dengue', 'seguimiento dengue', 'hospitalizados dengue'],
    keywords: ['dengue', 'hospitalizados', 'epidemiologia', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.seguimiento-dengue',
    featured: true,
  },

  // ── DATOS EN LÍNEA / SIGH ───────────────────────────────────────────────

  // Laboratorio Cultivos
  {
    id: 'sigh-mapa-microbiologico',
    title: 'Mapa Microbiológico',
    description: 'Mapa microbiológico del laboratorio de cultivos.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'vista',
    category: 'Laboratorio Cultivos',
    route: '/sigh/laboratorio-cultivos/mapa-microbiologico',
    breadcrumb: 'Datos en Línea → Laboratorio Cultivos',
    aliases: ['cultivos', 'microbiologia', 'antibiograma', 'resistencia bacteriana'],
    keywords: ['mapa', 'microbiologico', 'cultivo', 'laboratorio', 'bacteria', 'resistencia'],
    permissionKey: 'menu.sigh.laboratorio-cultivos.mapa-microbiologico',
  },

  // Monitoreo en Línea
  {
    id: 'sigh-informe-familia-pendientes',
    title: 'Informe Familia Pendientes',
    description: 'Monitoreo de informes familiares pendientes de atención.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Monitoreo en Línea',
    route: '/sigh/monitoreo-en-linea/informe-familia-pendientes',
    breadcrumb: 'Datos en Línea → Monitoreo en Línea',
    aliases: ['familia pendientes', 'informe familiar', 'pendientes familia'],
    keywords: ['informe', 'familia', 'pendiente', 'monitoreo'],
    permissionKey: 'menu.sigh.monitoreo-en-linea.informe-familia-pendientes',
    featured: true,
  },
  {
    id: 'sigh-sala-monitoreo-dengue-monitoreo',
    title: 'Monitoreo',
    description: 'Dashboard Power BI para seguimiento y sala de monitoreo de dengue.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'tablero',
    category: 'Sala Monitoreo Dengue',
    route: '/sigh/sala-monitoreo-dengue/monitoreo',
    breadcrumb: 'Datos en Línea → Sala Monitoreo Dengue',
    legacyName: 'Sala Monitoreo Dengue - Monitoreo',
    aliases: ['dengue', 'sala dengue', 'monitoreo dengue', 'sala monitoreo dengue'],
    keywords: ['dengue', 'monitoreo', 'sala', 'powerbi', 'epidemiologia'],
    permissionKey: 'menu.sigh.sala-monitoreo-dengue.monitoreo',
    featured: true,
  },

  // Exportar Registros
  {
    id: 'sigh-registros-nominales',
    title: 'Exportar Datos — Registros Nominales Diarios',
    description: 'Reportes diarios de pacientes hospitalizados, altas, fallecidos, camas y apertura de cuentas.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'exportable',
    category: 'Exportar Registros',
    route: '/sigh/exportar-registros/registros-nominales',
    breadcrumb: 'Datos en Línea → Exportar Registros',
    legacyName: 'Exportar Datos (registros nominales)',
    aliases: [
      'exportar datos',
      'hospitalizados',
      'altas',
      'fallecidos',
      'camas diario',
      'reporte diario hospitalizados',
      'reporte diario pacientes hospitalizados',
      'reporte diario pacientes alta',
      'reporte diario pacientes fallecidos',
      'reporte diario camas',
      'listado nominal fallecidos',
      'listado nominal altas',
      'listado nominal alta medica',
      'apertura cuentas',
      'listado usuarios apertura cuentas',
    ],
    keywords: ['exportar', 'datos', 'hospitalizado', 'alta', 'fallecido', 'cama', 'diario', 'nominal', 'apertura', 'cuenta'],
    permissionKey: 'menu.sigh.exportar-registros.registros-nominales',
    featured: true,
  },
  {
    id: 'sigh-registros-produccion',
    title: 'Zona de Descarga de Información por Periodos',
    description: 'Listados nominales por periodo con validación SISGALEN: programados, atendidos, emergencias, altas, fallecidos, historias clínicas.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'exportable',
    category: 'Exportar Registros',
    route: '/sigh/exportar-registros/registros-produccion',
    breadcrumb: 'Datos en Línea → Exportar Registros',
    legacyName: 'Zona de Descarga de Información por Periodos',
    aliases: [
      'zona descarga',
      'descarga periodos',
      'historias clinicas',
      'historias clinicas aperturadas',
      'recetas firma electronica',
      'firma electronica',
      'listado nominal programados',
      'listado nominal atendidos',
      'listado nominal emergencia',
      'ambulatorio nominal',
      'sisgalen',
      'hce',
    ],
    keywords: ['zona', 'descarga', 'periodo', 'nominal', 'historia', 'clinica', 'receta', 'firma', 'electronica', 'sisgalen', 'programado', 'atendido'],
    permissionKey: 'menu.sigh.exportar-registros.registros-produccion',
    featured: true,
  },

  // Producción de Actividades
  {
    id: 'sigh-produccion-medicos',
    title: 'Producción Médicos',
    description: 'Producción de actividades de médicos: consultas, procedimientos. Exportable en PDF y Excel.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'exportable',
    category: 'Producción de Actividades',
    route: '/sigh/produccion-actividades/produccion-medicos',
    breadcrumb: 'Datos en Línea → Producción de Actividades',
    legacyName: 'Producción Médicos — PDF / Excel',
    aliases: [
      'produccion medicos',
      'produccion medica',
      'produccion pdf',
      'produccion excel',
      'medicos pdf',
      'medicos excel',
      'actividades medicos',
    ],
    keywords: ['produccion', 'medico', 'actividad', 'pdf', 'excel', 'exportar'],
    permissionKey: 'menu.sigh.produccion-actividades.produccion-medicos',
    featured: true,
  },
  {
    id: 'sigh-produccion-obstetras',
    title: 'Producción Obstetras',
    description: 'Producción de actividades de obstetras con exportación en PDF y Excel.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'exportable',
    category: 'Producción de Actividades',
    route: '/sigh/produccion-actividades/produccion-obstetras',
    breadcrumb: 'Datos en Línea → Producción de Actividades',
    legacyName: 'Producción Obstetras — PDF / Excel',
    aliases: ['produccion obstetras', 'produccion obstetrica', 'obstetras pdf', 'obstetras excel'],
    keywords: ['produccion', 'obstetra', 'actividad', 'pdf', 'excel', 'exportar'],
    permissionKey: 'menu.sigh.produccion-actividades.produccion-obstetras',
    featured: false,
  },

  // Gestión Camas
  {
    id: 'sigh-monitoreo-camas',
    title: 'Monitoreo de Camas',
    description: 'Monitoreo en tiempo real del estado de camas hospitalarias.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/monitoreo-de-camas',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    aliases: ['monitoreo camas', 'camas tiempo real', 'estado camas', 'ocupacion camas'],
    keywords: ['monitoreo', 'cama', 'ocupacion', 'disponible', 'tiempo', 'real'],
    permissionKey: 'menu.sigh.gestion-camas.monitoreo-de-camas',
    featured: true,
  },
  {
    id: 'sigh-resumen-camas',
    title: 'Resumen de Camas',
    description: 'Resumen de camas por piso y servicio incluyendo Susalud.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'tablero',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/resumen-de-camas',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    legacyName: 'Resumen por Piso / Resumen Susalud',
    aliases: ['resumen camas', 'resumen piso', 'susalud', 'camas por piso', 'camas susalud'],
    keywords: ['resumen', 'cama', 'piso', 'susalud', 'disponible'],
    permissionKey: 'menu.sigh.gestion-camas.resumen-de-camas',
  },
  {
    id: 'sigh-ocupacion-cama',
    title: 'Porcentaje de Ocupación Cama',
    description: 'Porcentaje de ocupación de camas por servicio y periodo.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'tablero',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/porcentaje-de-ocupacion-cama',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    aliases: ['ocupacion cama', 'porcentaje camas', 'camas ocupadas'],
    keywords: ['ocupacion', 'cama', 'porcentaje', 'disponible'],
    permissionKey: 'menu.sigh.gestion-camas.porcentaje-de-ocupacion-cama',
  },
  {
    id: 'sigh-gestion-estancia-cama',
    title: 'Gestión Estancia Cama',
    description: 'Gestión de estancia por cama: días hospitalizados y rotación.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'tablero',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/gestion-estancia-cama',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    aliases: ['estancia cama', 'dias cama', 'rotacion cama', 'gestion estancia'],
    keywords: ['estancia', 'cama', 'dias', 'rotacion', 'gestion'],
    permissionKey: 'menu.sigh.gestion-camas.gestion-estancia-cama',
    featured: true,
  },

  // Atención al Usuario
  {
    id: 'sigh-gestion-citas',
    title: 'Gestión de Citas',
    description: 'Monitoreo de la gestión de citas médicas y disponibilidad.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/gestion-de-citas',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['gestion citas', 'citas disponibles', 'agenda citas'],
    keywords: ['gestion', 'cita', 'disponible', 'agenda', 'programacion'],
    permissionKey: 'menu.sigh.atencion-al-usuario.gestion-de-citas',
    featured: true,
  },
  {
    id: 'sigh-rol-consulta-externa',
    title: 'Rol Consulta Externa',
    description: 'Rol y programación de consulta externa por especialidad.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'vista',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/rol-consulta-externa',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['rol consulta', 'programacion consulta', 'rol medico'],
    keywords: ['rol', 'consulta', 'externa', 'programacion', 'especialidad'],
    permissionKey: 'menu.sigh.atencion-al-usuario.rol-consulta-externa',
  },
  {
    id: 'sigh-monitoreo-tickets',
    title: 'Monitoreo de Tickets',
    description: 'Monitoreo de tickets de ventanilla y atención al usuario.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/monitoreo-de-tickets',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    legacyName: 'Listado de Ticket de Ventanilla',
    aliases: ['tickets', 'ticket ventanilla', 'ticket admision', 'colas', 'turno', 'cola espera'],
    keywords: ['ticket', 'ventanilla', 'admision', 'cola', 'turno', 'monitoreo'],
    permissionKey: 'menu.sigh.atencion-al-usuario.monitoreo-de-tickets',
    featured: true,
  },
  {
    id: 'sigh-tiempos-espera',
    title: 'Tiempos de Espera',
    description: 'Monitoreo de tiempos de espera en ventanilla y consulta.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/tiempos-de-espera',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['tiempo espera', 'espera pacientes', 'demora atencion'],
    keywords: ['tiempo', 'espera', 'ventanilla', 'demora', 'atencion'],
    permissionKey: 'menu.sigh.atencion-al-usuario.tiempos-de-espera',
  },
  {
    id: 'sigh-monitoreo-ventanilla',
    title: 'Monitoreo Ventanilla',
    description: 'Monitoreo operativo de ventanilla de admisión y citas.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/monitoreo-ventanilla',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['ventanilla', 'admision', 'monitoreo admision'],
    keywords: ['ventanilla', 'admision', 'monitoreo', 'atencion', 'usuario'],
    permissionKey: 'menu.sigh.atencion-al-usuario.monitoreo-ventanilla',
  },

]

const dashboardEnhancements: Record<string, CatalogResourceEnhancement> = {
  'main-indicadores-eficiencia': {
    description: 'Tablero para evaluar eficiencia hospitalaria.',
    summary:
      'Evalua productividad, uso de consultorios, camas, sala de operaciones y laboratorio para seguimiento institucional.',
    questions: [
      '¿Cómo está la productividad médica?',
      '¿Cómo se están utilizando los consultorios?',
      '¿Cuál es el nivel de ocupación de camas?',
      '¿Cuál es el rendimiento de sala de operaciones?',
      '¿Cómo se comporta la producción de laboratorio?',
    ],
    mainIndicators: [
      'Productividad hora médico',
      'Rendimiento hora médico',
      'Utilización de consultorios físicos',
      'Promedio de permanencia cama',
      'Intervalo de sustitución cama',
      'Porcentaje de ocupación cama',
      'Rendimiento cama',
      'Rendimiento de sala de operaciones',
      'Exámenes de laboratorio',
    ],
    filters: ['Año', 'Mes', 'Servicio', 'Especialidad'],
    targetUsers: ['Dirección', 'Estadística', 'Planeamiento', 'Coordinadores asistenciales'],
    useCases: ['Analizar productividad médica', 'Revisar uso de camas', 'Monitorear producción de laboratorio'],
    aliases: [
      'indicadores',
      'eficiencia',
      'productividad',
      'hora médico',
      'rendimiento médico',
      'consultorios',
      'camas',
      'ocupación cama',
      'permanencia',
      'laboratorio',
      'sala de operaciones',
    ],
    keywords: [
      'indicador',
      'eficiencia',
      'productividad',
      'hora medico',
      'rendimiento medico',
      'consultorio',
      'cama',
      'ocupacion',
      'permanencia',
      'laboratorio',
      'sala operaciones',
    ],
    featured: true,
  },
  'main-indicadores-eficacia': {
    summary:
      'Evalua la eficacia de la atención mediante concentración en consulta externa y razón de emergencia por consulta externa.',
    questions: [
      '¿Cuál es la concentración de atenciones en consulta externa?',
      '¿Qué relación existe entre emergencia y consulta externa?',
      '¿Cómo se comporta la continuidad de atención?',
    ],
    mainIndicators: ['Concentración en consulta externa', 'Razón de emergencia por consulta externa'],
    filters: ['Año', 'Mes', 'Servicio'],
    targetUsers: ['Dirección', 'Estadística', 'Consulta externa'],
    useCases: ['Revisar continuidad de atención', 'Comparar emergencia y consulta externa'],
    aliases: ['indicadores', 'eficacia', 'concentración', 'consulta externa', 'razón emergencia', 'continuidad'],
    keywords: ['eficacia', 'concentracion', 'consulta externa', 'razon emergencia', 'continuidad', 'atenciones'],
  },
  'main-indicadores-calidad': {
    summary:
      'Revisa indicadores de calidad asistencial relacionados con mortalidad, cesáreas, cirugías suspendidas y muerte materna.',
    questions: [
      '¿Cuál es la tasa de mortalidad hospitalaria?',
      '¿Cómo se comportan las cesáreas?',
      '¿Cuántas cirugías fueron suspendidas?',
      '¿Existen registros de muerte materna?',
    ],
    mainIndicators: [
      'Tasa neta de mortalidad hospitalaria',
      'Mortalidad neonatal o perinatal',
      'Tasa de cesáreas',
      'Cirugías suspendidas',
      'Muerte materna',
    ],
    filters: ['Año', 'Mes', 'Servicio'],
    targetUsers: ['Calidad', 'Dirección', 'Estadística'],
    useCases: ['Revisar mortalidad hospitalaria', 'Monitorear cirugías suspendidas', 'Seguir muerte materna'],
    aliases: ['indicadores', 'calidad', 'mortalidad hospitalaria', 'cesáreas', 'cirugías suspendidas', 'muerte materna'],
    keywords: ['calidad', 'mortalidad', 'mortalidad hospitalaria', 'neonatal', 'perinatal', 'cesarea', 'cirugia suspendida', 'muerte materna'],
  },
  'main-consulta-externa': {
    description: 'Tablero para revisar la producción general de consulta externa.',
    summary:
      'Permite revisar producción por periodo, sexo, edad, departamento, especialidad y tipo de atención.',
    questions: [
      '¿Cuántas atenciones se realizaron en consulta externa?',
      '¿Qué especialidades concentran mayor producción?',
      '¿Cómo se distribuyen las atenciones por edad y sexo?',
      '¿Qué tipo de atención se registra?',
    ],
    mainIndicators: [
      'Atenciones de consulta externa',
      'Atenciones por sexo',
      'Atenciones por edad',
      'Atenciones por departamento',
      'Atenciones por especialidad',
      'Tipo de atención',
    ],
    filters: ['Año', 'Mes', 'Departamento', 'Especialidad', 'Tipo de atención'],
    targetUsers: ['Consulta externa', 'Estadística', 'Dirección'],
    useCases: ['Revisar producción ambulatoria', 'Analizar especialidades', 'Comparar atenciones por edad y sexo'],
    aliases: ['consulta externa', 'consultorios externos', 'ambulatoria', 'ce', 'especialidad', 'producción'],
    keywords: ['consulta externa', 'consultorios externos', 'atenciones', 'especialidad', 'departamento', 'produccion', 'edad', 'sexo', 'tipo atencion'],
    featured: true,
  },
  'main-consulta-externa-servicio': {
    summary:
      'Analiza atenciones por especialidad, horas programadas, horas efectivas, rendimiento hora médico, concentración mensual y productividad por servicio.',
    questions: [
      '¿Qué servicio tiene mayor producción?',
      '¿Cuántas horas fueron programadas y efectivas?',
      '¿Cuál es el rendimiento por hora médico?',
      '¿Cómo se comporta la concentración mensual?',
    ],
    mainIndicators: [
      'Atenciones por servicio',
      'Horas programadas',
      'Horas efectivas',
      'Rendimiento hora médico',
      'Concentración mensual',
      'Productividad por servicio',
    ],
    filters: ['Año', 'Mes', 'Servicio', 'Especialidad'],
    targetUsers: ['Consulta externa', 'Coordinadores de servicio', 'Estadística'],
    useCases: ['Comparar productividad por servicio', 'Revisar horas efectivas', 'Analizar rendimiento médico'],
    aliases: ['consulta externa por servicio', 'servicio', 'especialidad', 'horas programadas', 'horas efectivas', 'rendimiento médico', 'productividad'],
    keywords: ['consulta externa', 'servicio', 'especialidad', 'horas programadas', 'horas efectivas', 'rendimiento medico', 'productividad', 'concentracion'],
  },
  'main-consulta-externa-consultorio-profesional': {
    description: 'Vista de producción por consultorio, profesional y procedimiento.',
    summary:
      'Revisa producción por consultorio, profesional y procedimiento para analizar desempeño individual o por ambiente de atención.',
    questions: [
      '¿Qué profesional registra mayor producción?',
      '¿Qué consultorio concentra más atenciones?',
      '¿Qué procedimientos se realizan con mayor frecuencia?',
    ],
    mainIndicators: ['Producción por consultorio', 'Producción por profesional', 'Procedimientos realizados', 'Atenciones por ambiente'],
    filters: ['Año', 'Mes', 'Consultorio', 'Profesional', 'Procedimiento'],
    targetUsers: ['Consulta externa', 'Jefaturas de servicio', 'Estadística'],
    useCases: ['Analizar producción profesional', 'Revisar consultorios con mayor demanda', 'Identificar procedimientos frecuentes'],
    aliases: ['consultorio', 'profesional', 'médico', 'procedimiento', 'producción profesional', 'producción consultorio', 'consulta externa'],
    keywords: ['consultorio', 'profesional', 'medico', 'procedimiento', 'produccion profesional', 'produccion consultorio', 'consulta externa'],
  },
  'main-consulta-externa-monitoreo': {
    summary:
      'Monitorea atenciones presenciales, telemonitoreo y resumen de producción por modalidad.',
    questions: [
      '¿Cuántas atenciones fueron presenciales?',
      '¿Cuántas corresponden a telemonitoreo?',
      '¿Cómo se distribuye la producción por modalidad?',
    ],
    mainIndicators: ['Atenciones presenciales', 'Telemonitoreo', 'Producción por modalidad', 'Resumen operativo'],
    filters: ['Año', 'Mes', 'Modalidad', 'Servicio'],
    targetUsers: ['Consulta externa', 'Estadística', 'Coordinadores'],
    useCases: ['Monitorear producción operativa', 'Separar atenciones presenciales y telemonitoreo'],
    aliases: ['monitoreo consulta externa', 'presencial', 'telemonitoreo', 'modalidad', 'producción', 'atenciones'],
    keywords: ['monitoreo consulta externa', 'presencial', 'telemonitoreo', 'modalidad', 'produccion', 'atenciones'],
  },
  'main-consulta-externa-diagnosticos': {
    title: 'Consulta Externa - Diagnósticos Frecuentes',
    summary:
      'Identifica diagnósticos frecuentes por especialidad, servicio, edad, sexo, grupo etario y código CIE.',
    questions: [
      '¿Cuáles son los diagnósticos más frecuentes?',
      '¿Qué diagnósticos predominan por especialidad?',
      '¿Cómo se distribuyen los diagnósticos por edad o sexo?',
    ],
    mainIndicators: [
      'Diagnósticos frecuentes',
      'Diagnósticos por especialidad',
      'Diagnósticos por servicio',
      'Código CIE',
      'Distribución por edad y sexo',
      'Grupo etario',
    ],
    filters: ['Año', 'Mes', 'Especialidad', 'Servicio', 'Edad', 'Sexo', 'CIE'],
    targetUsers: ['Consulta externa', 'Epidemiología', 'Estadística'],
    useCases: ['Identificar morbilidad frecuente', 'Revisar diagnósticos por especialidad', 'Analizar diagnósticos por grupo etario'],
    aliases: ['diagnósticos frecuentes', 'cie', 'cie10', 'morbilidad', 'consulta externa', 'especialidad', 'grupo etario'],
    keywords: ['diagnosticos frecuentes', 'cie', 'cie10', 'morbilidad', 'consulta externa', 'especialidad', 'grupo etario', 'edad', 'sexo'],
  },
  'main-hospitalizacion': {
    summary:
      'Revisa indicadores hospitalarios de permanencia, intervalo de sustitución, porcentaje de ocupación cama y rendimiento cama.',
    questions: [
      '¿Cuál es la ocupación de camas?',
      '¿Cuál es el promedio de permanencia?',
      '¿Cuál es el rendimiento cama?',
      '¿Cómo se comporta la hospitalización por periodo?',
    ],
    mainIndicators: ['Promedio de permanencia', 'Intervalo de sustitución', 'Porcentaje de ocupación cama', 'Rendimiento cama', 'Hospitalización'],
    filters: ['Año', 'Mes', 'Servicio', 'Piso'],
    targetUsers: ['Hospitalización', 'Gestión de camas', 'Estadística'],
    useCases: ['Revisar ocupación de camas', 'Analizar permanencia', 'Monitorear rendimiento cama'],
    aliases: ['hospitalización', 'camas', 'ocupación cama', 'permanencia', 'intervalo de sustitución', 'rendimiento cama', 'egresos'],
    keywords: ['hospitalizacion', 'camas', 'ocupacion cama', 'permanencia', 'intervalo sustitucion', 'rendimiento cama', 'egresos'],
    featured: true,
  },
  'main-centro-obstetrico': {
    summary:
      'Revisa indicadores operativos del centro obstétrico relacionados con permanencia, camas, ocupación y rendimiento.',
    questions: [
      '¿Cómo se comporta la producción del centro obstétrico?',
      '¿Cuál es la ocupación y rendimiento del servicio?',
      '¿Qué indicadores obstétricos requieren seguimiento?',
    ],
    mainIndicators: ['Producción obstétrica', 'Permanencia', 'Ocupación', 'Rendimiento', 'Indicadores de centro obstétrico'],
    filters: ['Año', 'Mes', 'Servicio'],
    targetUsers: ['Obstetricia', 'Estadística', 'Dirección'],
    useCases: ['Revisar producción obstétrica', 'Monitorear ocupación', 'Seguir indicadores obstétricos'],
    aliases: ['centro obstétrico', 'obstetricia', 'partos', 'camas', 'ocupación', 'permanencia', 'rendimiento'],
    keywords: ['centro obstetrico', 'obstetricia', 'partos', 'camas', 'ocupacion', 'permanencia', 'rendimiento'],
    featured: false,
  },
  'main-triaje-admisionados': {
    summary:
      'Revisa pacientes nuevos en emergencia, prioridad de atención, condición, turno y horarios de atención.',
    questions: [
      '¿Cuántos pacientes nuevos ingresaron por emergencia?',
      '¿Qué prioridades de atención predominan?',
      '¿En qué turnos se concentra la demanda?',
      '¿Qué horarios tienen mayor ingreso?',
    ],
    mainIndicators: ['Pacientes nuevos', 'Prioridad de atención', 'Turno', 'Condición', 'Horario de atención'],
    filters: ['Año', 'Mes', 'Turno', 'Prioridad', 'Condición'],
    targetUsers: ['Emergencia', 'Admisión', 'Estadística'],
    useCases: ['Revisar admisionados en emergencia', 'Analizar triaje', 'Identificar turnos de mayor demanda'],
    aliases: ['triaje', 'admisionados', 'emergencia', 'prioridad', 'turno', 'pacientes nuevos', 'atención emergencia'],
    keywords: ['triaje', 'admisionados', 'emergencia', 'prioridad', 'turno', 'pacientes nuevos', 'atencion emergencia'],
  },
  'main-emergencia': {
    description: 'Tablero para revisar la producción general del servicio de emergencia.',
    summary:
      'Analiza atenciones por servicio, prioridad, reingresos, observación y pacientes pendientes de hospitalización.',
    questions: [
      '¿Cuántas atenciones de emergencia hubo?',
      '¿Qué servicios concentran mayor demanda?',
      '¿Cuántos pacientes quedaron en observación?',
      '¿Cuántos pacientes están pendientes de hospitalización?',
      '¿Cuántos reingresos se registraron?',
    ],
    mainIndicators: [
      'Atenciones de emergencia',
      'Atenciones por servicio',
      'Prioridad',
      'Reingresos',
      'Pacientes en observación',
      'Pendientes de hospitalización',
    ],
    filters: ['Año', 'Mes', 'Servicio', 'Prioridad', 'Turno'],
    targetUsers: ['Emergencia', 'Estadística', 'Dirección', 'Coordinadores asistenciales'],
    useCases: ['Revisar demanda de emergencia', 'Ver pacientes en observación', 'Identificar pendientes de hospitalización'],
    aliases: ['emergencia', 'urgencia', 'triaje', 'prioridad', 'reingreso', 'observación', 'pacientes pendientes', 'hospitalización'],
    keywords: ['emergencia', 'urgencia', 'triaje', 'prioridad', 'reingreso', 'observacion', 'pacientes pendientes', 'hospitalizacion', 'atencion emergencia'],
    featured: true,
  },
  'main-emergencia-por-servicio': {
    summary:
      'Revisa atenciones de emergencia por primer servicio, prioridad y condición de ingreso o egreso.',
    questions: [
      '¿Qué servicio recibe más atenciones de emergencia?',
      '¿Qué prioridades predominan por servicio?',
      '¿Cómo egresan los pacientes atendidos?',
    ],
    mainIndicators: ['Atenciones por primer servicio', 'Prioridad', 'Condición de ingreso', 'Condición de egreso'],
    filters: ['Año', 'Mes', 'Servicio', 'Prioridad', 'Condición'],
    targetUsers: ['Emergencia', 'Coordinadores', 'Estadística'],
    useCases: ['Comparar demanda por servicio', 'Revisar prioridades por especialidad', 'Analizar egresos de emergencia'],
    aliases: ['emergencia por servicio', 'primer servicio', 'prioridad', 'condición ingreso', 'condición egreso', 'urgencia'],
    keywords: ['emergencia por servicio', 'primer servicio', 'prioridad', 'condicion ingreso', 'condicion egreso', 'urgencia'],
  },
  'main-cuidados-criticos': {
    summary:
      'Revisa indicadores de UCE y UCI relacionados con permanencia, intervalo de sustitución, ocupación cama y rendimiento cama.',
    questions: [
      '¿Cuál es la ocupación de camas UCI o UCE?',
      '¿Cuál es el promedio de permanencia?',
      '¿Cómo se comporta el rendimiento cama en cuidados críticos?',
    ],
    mainIndicators: ['Promedio de permanencia', 'Intervalo de sustitución', 'Ocupación cama', 'Rendimiento cama', 'Indicadores UCE', 'Indicadores UCI'],
    filters: ['Año', 'Mes', 'Unidad', 'Servicio'],
    targetUsers: ['Cuidados críticos', 'UCI', 'UCE', 'Estadística'],
    useCases: ['Revisar ocupación UCI/UCE', 'Analizar permanencia en críticos', 'Monitorear rendimiento cama'],
    aliases: ['uci', 'uce', 'cuidados críticos', 'camas críticas', 'ocupación cama', 'permanencia', 'rendimiento cama'],
    keywords: ['uci', 'uce', 'cuidados criticos', 'camas criticas', 'ocupacion cama', 'permanencia', 'rendimiento cama'],
    featured: false,
  },
  'main-centro-quirurgico': {
    summary:
      'Revisa rendimiento de salas de operaciones, intervenciones por turno, tipo de cirugía, procedencia, especialidad, sala y tipo de procedimiento.',
    questions: [
      '¿Cuántas cirugías se realizaron?',
      '¿Qué sala quirúrgica tiene mayor producción?',
      '¿Qué especialidades concentran más intervenciones?',
      '¿Qué tipos de cirugía predominan?',
    ],
    mainIndicators: [
      'Rendimiento de sala de operaciones',
      'Intervenciones quirúrgicas',
      'Cirugías por turno',
      'Tipo de cirugía',
      'Procedencia',
      'Especialidad',
      'Sala quirúrgica',
      'Tipo de procedimiento',
    ],
    filters: ['Año', 'Mes', 'Turno', 'Especialidad', 'Sala', 'Tipo de cirugía'],
    targetUsers: ['Centro quirúrgico', 'Dirección', 'Estadística'],
    useCases: ['Revisar producción quirúrgica', 'Analizar sala de operaciones', 'Identificar cirugías suspendidas o procedimientos'],
    aliases: ['centro quirúrgico', 'sala de operaciones', 'cirugía', 'intervenciones', 'sala quirúrgica', 'procedimiento', 'especialidad', 'turno'],
    keywords: ['centro quirurgico', 'sala de operaciones', 'cirugia', 'intervenciones', 'sala quirurgica', 'procedimiento', 'especialidad', 'turno'],
    featured: true,
  },
  'main-laboratorio': {
    summary:
      'Revisa producción de laboratorio por mes, tipo de prueba, servicio, procedencia y volumen de exámenes.',
    questions: [
      '¿Cuántos exámenes de laboratorio se realizaron?',
      '¿Qué pruebas son más frecuentes?',
      '¿Qué servicios solicitan más exámenes?',
      '¿Cómo evoluciona la producción mensual?',
    ],
    mainIndicators: ['Exámenes de laboratorio', 'Producción mensual', 'Tipo de prueba', 'Servicio solicitante', 'Procedencia'],
    filters: ['Año', 'Mes', 'Prueba', 'Servicio', 'Procedencia'],
    targetUsers: ['Laboratorio', 'Apoyo al diagnóstico', 'Estadística'],
    useCases: ['Revisar producción de laboratorio', 'Identificar pruebas frecuentes', 'Comparar servicios solicitantes'],
    aliases: ['laboratorio', 'exámenes', 'pruebas', 'análisis', 'producción laboratorio', 'servicio solicitante', 'procedencia'],
    keywords: ['laboratorio', 'examenes', 'pruebas', 'analisis', 'produccion laboratorio', 'servicio solicitante', 'procedencia'],
    featured: false,
  },
  'main-imagenologia': {
    summary:
      'Revisa producción de imágenes, estudios por tipo, servicio, procedencia y comportamiento mensual.',
    questions: [
      '¿Cuántos estudios de imagen se realizaron?',
      '¿Qué tipos de estudio son más frecuentes?',
      '¿Qué servicios solicitan más imágenes?',
      '¿Cómo evoluciona la producción mensual?',
    ],
    mainIndicators: ['Estudios de imagen', 'Producción mensual', 'Tipo de estudio', 'Servicio solicitante', 'Procedencia'],
    filters: ['Año', 'Mes', 'Tipo de estudio', 'Servicio', 'Procedencia'],
    targetUsers: ['Imagenología', 'Apoyo al diagnóstico', 'Estadística'],
    useCases: ['Revisar producción de imágenes', 'Identificar estudios frecuentes', 'Comparar servicios solicitantes'],
    aliases: ['imagenología', 'imágenes', 'radiología', 'ecografía', 'tomografía', 'estudios', 'producción imágenes', 'diagnóstico por imágenes'],
    keywords: ['imagenologia', 'imagenes', 'radiologia', 'ecografia', 'tomografia', 'estudios', 'produccion imagenes', 'diagnostico por imagenes'],
  },
  'main-incidentes-eventos-adversos': {
    summary:
      'Revisa eventos adversos e incidentes por servicio, unidad, severidad, tipo, categoría y detalle de notificación.',
    questions: [
      '¿Cuántos incidentes fueron notificados?',
      '¿Qué tipos de eventos adversos se registran?',
      '¿Qué servicios notifican más eventos?',
      '¿Cuál es la severidad de los casos?',
    ],
    mainIndicators: ['Incidentes notificados', 'Eventos adversos', 'Severidad', 'Tipo de evento', 'Categoría', 'Servicio o unidad notificante'],
    filters: ['Año', 'Mes', 'Servicio', 'Unidad', 'Severidad', 'Tipo de evento'],
    targetUsers: ['Calidad', 'Seguridad del paciente', 'Dirección'],
    useCases: ['Revisar incidentes notificados', 'Analizar eventos adversos', 'Priorizar casos por severidad'],
    aliases: ['incidentes', 'eventos adversos', 'seguridad del paciente', 'severidad', 'notificación', 'riesgo', 'unidad notificante'],
    keywords: ['incidentes', 'eventos adversos', 'seguridad paciente', 'severidad', 'notificacion', 'riesgo', 'unidad notificante'],
  },
  'main-tamizaje-neonatal': {
    summary:
      'Revisa registros de tamizaje neonatal, prueba de talón, pendientes, tiempos de toma y seguimiento por recién nacido.',
    questions: [
      '¿Cuántos recién nacidos tienen tamizaje?',
      '¿Cuántos están pendientes?',
      '¿Cuánto tiempo toma realizar la prueba?',
      '¿Qué registros requieren seguimiento?',
    ],
    mainIndicators: ['Tamizaje neonatal', 'Prueba de talón', 'Pendientes de tamizaje', 'Tiempo de toma', 'Seguimiento de recién nacido'],
    filters: ['Año', 'Mes', 'Servicio', 'Estado'],
    targetUsers: ['Enfermería', 'Neonatología', 'Estadística'],
    useCases: ['Revisar tamizaje neonatal', 'Detectar pendientes', 'Seguir prueba de talón'],
    aliases: ['tamizaje neonatal', 'prueba de talón', 'recién nacido', 'enfermería', 'pendientes', 'neonatología'],
    keywords: ['tamizaje neonatal', 'prueba talon', 'recien nacido', 'enfermeria', 'pendientes', 'neonatologia'],
  },
  'main-extraccion-lm': {
    title: 'Extracción de Leche Materna',
    summary:
      'Revisa registros de extracción de leche materna y producción relacionada a neonatología.',
    questions: [
      '¿Cuántos registros de extracción existen?',
      '¿Cómo se comporta la producción de leche materna?',
      '¿Qué seguimiento se realiza en neonatología?',
    ],
    mainIndicators: ['Extracción de leche materna', 'Producción registrada', 'Seguimiento neonatal', 'Registros de enfermería'],
    filters: ['Año', 'Mes', 'Servicio'],
    targetUsers: ['Enfermería', 'Neonatología'],
    useCases: ['Revisar extracción de leche materna', 'Analizar producción registrada', 'Seguir registros neonatales'],
    aliases: ['leche materna', 'extracción', 'neonatología', 'enfermería', 'banco de leche', 'recién nacido'],
    keywords: ['leche materna', 'extraccion', 'neonatologia', 'enfermeria', 'banco leche', 'recien nacido'],
  },
  'main-defunciones': {
    summary:
      'Revisa defunciones por servicio, sexo, edad, diagnóstico, condición y comportamiento mensual.',
    questions: [
      '¿Cuántas defunciones se registraron?',
      '¿Qué servicios concentran más defunciones?',
      '¿Qué diagnósticos aparecen con mayor frecuencia?',
      '¿Cómo se distribuyen por edad y sexo?',
    ],
    mainIndicators: ['Defunciones', 'Defunciones por servicio', 'Defunciones por diagnóstico', 'Distribución por edad', 'Distribución por sexo', 'Comportamiento mensual'],
    filters: ['Año', 'Mes', 'Servicio', 'Diagnóstico', 'Sexo', 'Edad'],
    targetUsers: ['Hechos vitales', 'Estadística', 'Dirección'],
    useCases: ['Revisar mortalidad', 'Analizar defunciones por servicio', 'Identificar diagnósticos frecuentes'],
    aliases: ['defunciones', 'fallecidos', 'mortalidad', 'diagnóstico', 'servicio', 'edad', 'sexo'],
    keywords: ['defunciones', 'fallecidos', 'mortalidad', 'diagnostico', 'servicio', 'edad', 'sexo'],
    featured: false,
  },
  'main-inconsistencia-cdef': {
    summary:
      'Monitorea inconsistencias entre registros de certificado de defunción y defunción general.',
    questions: [
      '¿Qué registros presentan inconsistencias?',
      '¿Qué certificados requieren revisión?',
      '¿Qué diferencias existen entre fuentes?',
    ],
    mainIndicators: ['Inconsistencias CDEF', 'Certificado de defunción', 'Defunción general', 'Validación de registros'],
    filters: ['Año', 'Mes', 'Estado'],
    targetUsers: ['Hechos vitales', 'Estadística'],
    useCases: ['Validar certificados de defunción', 'Detectar inconsistencias', 'Comparar fuentes de registro'],
    aliases: ['cdef', 'certificado defunción', 'inconsistencia', 'defunciones', 'validación', 'registros'],
    keywords: ['cdef', 'certificado defuncion', 'inconsistencia', 'defunciones', 'validacion', 'registros'],
  },
  'main-nacimientos': {
    summary:
      'Revisa nacidos vivos por sexo, peso, edad gestacional, tipo de parto, profesional y participación institucional.',
    questions: [
      '¿Cuántos nacimientos se registraron?',
      '¿Cómo se distribuyen por sexo y peso?',
      '¿Qué tipos de parto predominan?',
      '¿Qué profesionales participaron?',
    ],
    mainIndicators: ['Nacidos vivos', 'Sexo del recién nacido', 'Peso', 'Edad gestacional', 'Tipo de parto', 'Profesional', 'Participación institucional'],
    filters: ['Año', 'Mes', 'Sexo', 'Tipo de parto', 'Profesional'],
    targetUsers: ['Hechos vitales', 'Obstetricia', 'Estadística'],
    useCases: ['Revisar nacimientos', 'Analizar tipo de parto', 'Evaluar peso y edad gestacional'],
    aliases: ['nacimientos', 'nacidos vivos', 'recién nacido', 'parto', 'peso', 'edad gestacional', 'obstetricia'],
    keywords: ['nacimientos', 'nacidos vivos', 'recien nacido', 'parto', 'peso', 'edad gestacional', 'obstetricia'],
  },
  'main-sala-inteligente-emergencia': {
    title: 'Sala Inteligente - Indicadores de Emergencia',
    summary:
      'Revisa indicadores de emergencia, atenciones, prioridad, tiempos, tipo de ingreso, diagnóstico y concentración de demanda.',
    questions: [
      '¿Cómo se comporta la emergencia en tiempo operativo?',
      '¿Qué prioridades predominan?',
      '¿Cuáles son los diagnósticos frecuentes?',
      '¿Dónde se concentra la demanda?',
    ],
    mainIndicators: ['Atenciones de emergencia', 'Prioridad', 'Tiempos de atención', 'Tipo de ingreso', 'Diagnósticos', 'Concentración de demanda'],
    filters: ['Periodo', 'Prioridad', 'Tipo de ingreso', 'Diagnóstico'],
    targetUsers: ['Emergencia', 'Sala inteligente', 'Dirección'],
    useCases: ['Monitorear emergencia', 'Revisar tiempos de atención', 'Identificar diagnósticos frecuentes'],
    aliases: ['sala inteligente', 'emergencia', 'indicadores emergencia', 'prioridad', 'tiempos', 'diagnóstico', 'demanda'],
    keywords: ['sala inteligente', 'emergencia', 'indicadores emergencia', 'prioridad', 'tiempos', 'diagnostico', 'demanda'],
  },
  'main-sala-inteligente-referencia-ce': {
    summary:
      'Revisa referencias de consulta externa aceptadas, rechazadas, no coordinadas, motivos, IPRESS origen, especialidad, producto, hito y oportunidad.',
    questions: [
      '¿Cuántas referencias fueron aceptadas?',
      '¿Cuántas fueron rechazadas?',
      '¿Qué IPRESS generan más referencias?',
      '¿Qué especialidades reciben más referencias?',
      '¿Cuáles son los motivos de rechazo?',
    ],
    mainIndicators: ['Referencias aceptadas', 'Referencias rechazadas', 'Referencias no coordinadas', 'Motivos de rechazo', 'IPRESS origen', 'Especialidad', 'Producto o hito', 'Oportunidad'],
    filters: ['Año', 'Mes', 'IPRESS', 'Especialidad', 'Estado', 'Motivo'],
    targetUsers: ['Referencia', 'Consulta externa', 'Articulación prestacional'],
    useCases: ['Revisar referencias rechazadas', 'Analizar IPRESS origen', 'Seguir oportunidad de atención'],
    aliases: ['referencias', 'referencia consulta externa', 'aceptadas', 'rechazadas', 'no coordinadas', 'ipress', 'especialidad', 'oportunidad', 'hito', 'producto'],
    keywords: ['referencias', 'referencia consulta externa', 'aceptadas', 'rechazadas', 'no coordinadas', 'ipress', 'especialidad', 'oportunidad', 'hito', 'producto'],
    featured: true,
  },
  'main-sala-inteligente-referencia-emergencia': {
    summary:
      'Revisa referencias desde emergencia, incluyendo aceptadas, rechazadas, suspendidas, no coordinadas, diagnóstico frecuente e IPRESS destino u origen.',
    questions: [
      '¿Cuántas referencias de emergencia se registraron?',
      '¿Cuántas fueron aceptadas o rechazadas?',
      '¿Qué diagnósticos motivan más referencias?',
      '¿Qué IPRESS participan con mayor frecuencia?',
    ],
    mainIndicators: ['Referencias de emergencia', 'Referencias aceptadas', 'Referencias rechazadas', 'Referencias suspendidas', 'Referencias no coordinadas', 'Diagnósticos frecuentes', 'IPRESS destino', 'IPRESS origen'],
    filters: ['Año', 'Mes', 'IPRESS', 'Estado', 'Diagnóstico'],
    targetUsers: ['Emergencia', 'Referencia', 'Articulación prestacional'],
    useCases: ['Revisar referencias de emergencia', 'Identificar rechazadas o suspendidas', 'Analizar diagnósticos frecuentes'],
    aliases: ['referencia emergencia', 'referencias', 'emergencia', 'aceptadas', 'rechazadas', 'suspendidas', 'no coordinadas', 'diagnóstico', 'ipress'],
    keywords: ['referencia emergencia', 'referencias', 'emergencia', 'aceptadas', 'rechazadas', 'suspendidas', 'no coordinadas', 'diagnostico', 'ipress'],
    featured: true,
  },
  'main-sala-inteligente-interconsulta': {
    summary:
      'Revisa solicitudes de interconsulta, tiempos, especialidades solicitantes, especialidades de respuesta y ranking de servicios.',
    questions: [
      '¿Cuántas interconsultas se solicitaron?',
      '¿Qué especialidades solicitan más interconsultas?',
      '¿Qué especialidades responden más?',
      '¿Cuánto tiempo demora la respuesta?',
    ],
    mainIndicators: ['Solicitudes de interconsulta', 'Tiempo de respuesta', 'Especialidad solicitante', 'Especialidad que responde', 'Ranking de servicios'],
    filters: ['Año', 'Mes', 'Especialidad solicitante', 'Especialidad de respuesta'],
    targetUsers: ['Hospitalización', 'Especialidades', 'Dirección'],
    useCases: ['Revisar interconsultas hospitalarias', 'Medir tiempos de respuesta', 'Comparar especialidades'],
    aliases: ['interconsulta', 'interconsulta hospitalaria', 'especialidad solicitante', 'respuesta', 'tiempo de respuesta', 'servicios'],
    keywords: ['interconsulta', 'interconsulta hospitalaria', 'especialidad solicitante', 'respuesta', 'tiempo respuesta', 'servicios'],
  },
  'main-sala-inteligente-enfermeria': {
    summary:
      'Revisa registros e indicadores de enfermería relacionados con escalas NEMS, NSRAS, TISS, Braden, LPP adulto y LPP pediátrico.',
    questions: [
      '¿Qué escalas de enfermería se están registrando?',
      '¿Qué pacientes presentan riesgo según Braden?',
      '¿Cómo se comportan los registros NEMS, TISS o NSRAS?',
      '¿Qué registros de LPP requieren seguimiento?',
    ],
    mainIndicators: ['Escala NEMS', 'Escala NSRAS', 'Escala TISS', 'Escala Braden', 'LPP adulto', 'LPP pediátrico', 'Registros de enfermería'],
    filters: ['Año', 'Mes', 'Servicio', 'Escala'],
    targetUsers: ['Enfermería', 'Cuidados críticos', 'Calidad'],
    useCases: ['Revisar indicadores de enfermería', 'Seguir riesgo Braden', 'Monitorear LPP'],
    aliases: ['enfermería', 'nems', 'nsras', 'tiss', 'braden', 'lpp', 'lesión por presión', 'riesgo', 'escalas'],
    keywords: ['enfermeria', 'nems', 'nsras', 'tiss', 'braden', 'lpp', 'lesion por presion', 'riesgo', 'escalas'],
  },
  'main-sala-inteligente-isq': {
    title: 'Indicadores ISQ - Endometritis',
    summary:
      'Revisa seguimiento de infección de sitio quirúrgico, endometritis, incidencia, cirugías, procedimientos y casos por grupo.',
    questions: [
      '¿Cuántos casos de ISQ se registran?',
      '¿Cuál es la incidencia de endometritis?',
      '¿Qué procedimientos se relacionan con los casos?',
      '¿Cómo se comportan los casos por grupo?',
    ],
    mainIndicators: ['Infección de sitio quirúrgico', 'Endometritis', 'Incidencia', 'Cirugías', 'Procedimientos', 'Casos por grupo'],
    filters: ['Año', 'Mes', 'Procedimiento', 'Grupo'],
    targetUsers: ['Epidemiología', 'Centro quirúrgico', 'Calidad'],
    useCases: ['Revisar ISQ', 'Analizar endometritis', 'Seguir procedimientos relacionados'],
    aliases: ['isq', 'infección sitio quirúrgico', 'endometritis', 'incidencia', 'cirugía', 'procedimiento', 'epidemiología'],
    keywords: ['isq', 'infeccion sitio quirurgico', 'endometritis', 'incidencia', 'cirugia', 'procedimiento', 'epidemiologia'],
  },
  'main-sala-inteligente-vacunas': {
    summary:
      'Revisa la estrategia de inmunizaciones, aplicaciones por vacuna, dosis, edad, grupo y tipo de seguro.',
    questions: [
      '¿Cuántas vacunas se aplicaron?',
      '¿Qué vacunas se aplican con mayor frecuencia?',
      '¿Cómo se distribuyen por edad o grupo?',
      '¿Qué tipo de seguro tienen los pacientes vacunados?',
    ],
    mainIndicators: ['Vacunas aplicadas', 'Tipo de vacuna', 'Dosis', 'Edad', 'Grupo poblacional', 'Tipo de seguro'],
    filters: ['Año', 'Mes', 'Vacuna', 'Dosis', 'Edad', 'Seguro'],
    targetUsers: ['Enfermería', 'Inmunizaciones', 'Epidemiología'],
    useCases: ['Revisar vacunas aplicadas', 'Analizar dosis por grupo', 'Seguir estrategia sanitaria'],
    aliases: ['vacunas', 'inmunizaciones', 'enfermería', 'dosis', 'edad', 'seguro', 'estrategia sanitaria'],
    keywords: ['vacunas', 'inmunizaciones', 'enfermeria', 'dosis', 'edad', 'seguro', 'estrategia sanitaria'],
  },
  'main-sala-inteligente-iaas': {
    title: 'Monitoreo IAAS',
    summary:
      'Revisa infecciones asociadas a la atención en salud, densidad de incidencia, casos por servicio, días de riesgo, dispositivos y evolución mensual.',
    questions: [
      '¿Cuántos casos de IAAS se registran?',
      '¿Cuál es la densidad de incidencia?',
      '¿Qué servicios concentran más casos?',
      '¿Qué dispositivos están asociados?',
      '¿Cómo evoluciona mensualmente?',
    ],
    mainIndicators: ['IAAS', 'Infecciones asociadas a la atención en salud', 'Densidad de incidencia', 'Casos por servicio', 'Días de riesgo', 'Dispositivos', 'Evolución mensual'],
    filters: ['Año', 'Mes', 'Servicio', 'Dispositivo'],
    targetUsers: ['Epidemiología', 'IAAS', 'Calidad'],
    useCases: ['Revisar infecciones IAAS', 'Monitorear densidad de incidencia', 'Analizar dispositivos asociados'],
    aliases: ['iaas', 'infecciones', 'infección intrahospitalaria', 'densidad de incidencia', 'dispositivos', 'días de riesgo', 'epidemiología', 'vigilancia'],
    keywords: ['iaas', 'infecciones', 'infeccion intrahospitalaria', 'densidad incidencia', 'dispositivos', 'dias riesgo', 'epidemiologia', 'vigilancia'],
    featured: true,
  },
  'main-tamizaje-salud-mental': {
    summary:
      'Revisa tamizajes de salud mental relacionados con violencia familiar, deterioro cognitivo, problemas del neurodesarrollo, maltrato infantil y trastornos mentales.',
    questions: [
      '¿Cuántos tamizajes de salud mental se realizaron?',
      '¿Qué tipos de tamizaje se registran?',
      '¿Qué grupos requieren seguimiento?',
      '¿Cómo se distribuyen los casos por condición evaluada?',
    ],
    mainIndicators: ['Tamizaje de salud mental', 'Violencia familiar', 'Deterioro cognitivo', 'Problemas del neurodesarrollo', 'Maltrato infantil', 'Trastornos mentales'],
    filters: ['Año', 'Mes', 'Tipo de tamizaje', 'Condición'],
    targetUsers: ['Salud mental', 'Estrategias sanitarias', 'Estadística'],
    useCases: ['Revisar tamizajes de salud mental', 'Seguir violencia familiar', 'Analizar deterioro cognitivo o neurodesarrollo'],
    aliases: ['salud mental', 'tamizaje', 'violencia familiar', 'deterioro cognitivo', 'neurodesarrollo', 'maltrato infantil', 'trastornos mentales'],
    keywords: ['salud mental', 'tamizaje', 'violencia familiar', 'deterioro cognitivo', 'neurodesarrollo', 'maltrato infantil', 'trastornos mentales'],
    featured: true,
  },
  'main-salud-mental-reportes': {
    featured: false,
  },
  'main-monitoreo-citas': {
    summary:
      'Revisa atención de citas por departamento, especialidad, consultorio, médico, turno y estado de atención.',
    questions: [
      '¿Cuántas citas fueron atendidas?',
      '¿Qué especialidades concentran más citas?',
      '¿Qué médicos o consultorios tienen mayor carga?',
      '¿Cómo se distribuyen por turno?',
    ],
    mainIndicators: ['Citas atendidas', 'Citas por departamento', 'Citas por especialidad', 'Citas por consultorio', 'Médico', 'Turno', 'Estado de atención'],
    filters: ['Año', 'Mes', 'Departamento', 'Especialidad', 'Consultorio', 'Médico', 'Turno'],
    targetUsers: ['Consulta externa', 'Articulación prestacional', 'Admisión'],
    useCases: ['Monitorear citas atendidas', 'Revisar carga por médico', 'Analizar turnos y consultorios'],
    aliases: ['citas', 'monitoreo citas', 'especialidad', 'consultorio', 'médico', 'turno', 'estado de atención'],
    keywords: ['citas', 'monitoreo citas', 'especialidad', 'consultorio', 'medico', 'turno', 'estado atencion'],
    featured: true,
  },
  'main-citas-reprogramadas': {
    title: 'Indicador Citas Reprogramadas',
    summary:
      'Revisa citas reprogramadas, motivos, especialidad y cantidad de reprogramaciones.',
    questions: [
      '¿Cuántas citas fueron reprogramadas?',
      '¿Qué motivos generan más reprogramaciones?',
      '¿Qué especialidades concentran más cambios?',
    ],
    mainIndicators: ['Citas reprogramadas', 'Motivo de reprogramación', 'Especialidad', 'Cantidad de reprogramaciones'],
    filters: ['Año', 'Mes', 'Especialidad', 'Motivo'],
    targetUsers: ['Articulación prestacional', 'Consulta externa', 'Admisión'],
    useCases: ['Revisar citas reprogramadas', 'Identificar motivos frecuentes', 'Comparar especialidades con cambios'],
    aliases: ['citas reprogramadas', 'reprogramación', 'motivos', 'especialidad', 'citas', 'indicador citas'],
    keywords: ['citas reprogramadas', 'reprogramacion', 'motivos', 'especialidad', 'citas', 'indicador citas'],
  },
  'main-accidente-transito': {
    summary:
      'Sala situacional VEA para revisar lesionados por accidente de tránsito, edad, sexo, grupo etario, traslado, severidad, día y hora del accidente.',
    questions: [
      '¿Cuántos lesionados por accidente de tránsito se registraron?',
      '¿Cómo se distribuyen por edad y sexo?',
      '¿Qué severidad presentan los casos?',
      '¿En qué días y horas ocurren más accidentes?',
    ],
    mainIndicators: ['Accidentes de tránsito', 'Lesionados', 'Edad', 'Sexo', 'Grupo etario', 'Traslado', 'Severidad', 'Día del accidente', 'Hora del accidente'],
    filters: ['Año', 'Mes', 'Edad', 'Sexo', 'Severidad', 'Traslado'],
    targetUsers: ['Epidemiología', 'Emergencia', 'Sala situacional'],
    useCases: ['Revisar lesionados por accidente', 'Analizar severidad', 'Monitorear sala situacional VEA'],
    aliases: ['accidente de tránsito', 'accidentes', 'lesionados', 'vea', 'severidad', 'traslado', 'grupo etario', 'epidemiología', 'sala situacional'],
    keywords: ['accidente de transito', 'accidentes', 'lesionados', 'vea', 'severidad', 'traslado', 'grupo etario', 'epidemiologia', 'sala situacional'],
  },
  'main-pacientes-oncologicos': {
    title: 'Pacientes Oncológicos',
    description: 'Exportación de pacientes con diagnóstico oncológico desde el reporte legacy de UIS.',
    category: 'Epidemiología',
    breadcrumb: 'Reporteador -> Epidemiología',
    legacyName: 'Búsqueda de Pacientes Oncológicos',
    aliases: ['oncológicos', 'bai onco', 'pacientes cáncer', 'oncología'],
    keywords: ['oncologico', 'oncologia', 'cancer', 'bai', 'epidemiologia', 'exportar'],
    featured: true,
  },
  'main-pfa-sifilis-sarampion': {
    title: 'PFA, Sífilis y Sarampión',
    description: 'Exportación de PFA, sífilis, sarampión, rubéola y SRC.',
    category: 'Epidemiología',
    breadcrumb: 'Reporteador -> Epidemiología',
    legacyName: 'PFA/Sífilis/Sarampión',
    aliases: ['pfa', 'sífilis', 'sarampión', 'rubéola', 'src'],
    keywords: ['pfa', 'sifilis', 'sarampion', 'rubeola', 'src', 'epidemiologia', 'exportar'],
    featured: false,
  },
  'main-isqx': {
    description: 'Monitoreo y exportación de infección del sitio quirúrgico.',
    category: 'Epidemiología',
    breadcrumb: 'Reporteador -> Epidemiología',
    aliases: ['bai isqx', 'isq', 'infección sitio quirúrgico', 'endometritis'],
    keywords: ['isqx', 'isq', 'infeccion', 'quirurgico', 'endometritis', 'epidemiologia', 'exportar'],
    featured: false,
  },
  'main-mordedura-canina': {
    description: 'Exportación de pacientes con diagnósticos relacionados a mordedura canina.',
    category: 'Epidemiología',
    breadcrumb: 'Reporteador -> Epidemiología',
    featured: false,
  },
  'main-cirugia-procedimiento': {
    title: 'Cirugía Procedimiento',
    description: 'Exportación de procedimientos quirúrgicos por periodo.',
    category: 'Epidemiología',
    breadcrumb: 'Reporteador -> Epidemiología',
    legacyName: 'Cirugía Procedimiento',
    aliases: ['cirugía procedimiento', 'procedimientos quirúrgicos'],
    keywords: ['cirugia', 'procedimiento', 'quirurgico', 'epidemiologia', 'exportar'],
    featured: false,
  },
  'main-seguimiento-dengue': {
    description: 'Exportación de pacientes hospitalizados con dengue.',
    category: 'Epidemiología',
    breadcrumb: 'Reporteador -> Epidemiología',
    featured: true,
  },
  'main-registros-procesados': {
    summary:
      'Exportable por periodo para descargar BAI - Morbilidad Materna Extrema y pacientes con diagnostico A97.0 - dengue sin signos de alarma.',
    questions: [
      '¿Como exporto BAI - Morbilidad Materna Extrema?',
      '¿Donde descargo pacientes con diagnostico A97.0?',
      '¿Como obtengo registros procesados por periodo?',
    ],
    mainIndicators: [
      'BAI - Morbilidad Materna Extrema',
      'Dengue sin signos de alarma',
      'Diagnostico A97.0',
      'Registros procesados',
    ],
    filters: ['Fecha inicio', 'Fecha fin'],
    targetUsers: ['Epidemiologia', 'Estadistica', 'Unidad de Inteligencia Sanitaria'],
    useCases: [
      'Exportar morbilidad materna extrema',
      'Exportar pacientes con diagnostico A97.0',
      'Descargar registros procesados por periodo',
    ],
    aliases: [
      'bai morbilidad materna extrema',
      'morbilidad materna extrema',
      'dengue sin signos de alarma',
      'diagnostico a97.0',
      'a97.0',
    ],
    keywords: [
      'bai',
      'morbilidad',
      'materna',
      'dengue',
      'sin signos de alarma',
      'a97.0',
      'diagnostico',
      'exportable',
    ],
    featured: false,
  },
  'main-lavado-manos': {
    featured: false,
  },
  'sigh-informe-familia-pendientes': {
    featured: false,
  },
  'sigh-sala-monitoreo-dengue-monitoreo': {
    featured: false,
  },
  'sigh-registros-nominales': {
    featured: false,
  },
  'sigh-registros-produccion': {
    featured: false,
  },
  'sigh-produccion-medicos': {
    featured: false,
  },
  'sigh-produccion-obstetras': {
    featured: false,
  },
  'sigh-monitoreo-camas': {
    title: 'Gestión de Camas',
    featured: true,
  },
  'sigh-gestion-estancia-cama': {
    featured: false,
  },
  'sigh-gestion-citas': {
    featured: false,
  },
  'sigh-monitoreo-tickets': {
    featured: false,
  },
}

function mergeCatalogArrays(baseValues: string[], enhancementValues?: string[]): string[] {
  if (!enhancementValues) return baseValues

  return Array.from(new Set([...baseValues, ...enhancementValues]))
}

export const navigationCatalog: CatalogResource[] = navigationCatalogBase.map((resource) => {
  const enhancement = dashboardEnhancements[resource.id]
  if (!enhancement) return resource

  return {
    ...resource,
    ...enhancement,
    aliases: mergeCatalogArrays(resource.aliases, enhancement.aliases),
    keywords: mergeCatalogArrays(resource.keywords, enhancement.keywords),
  }
})

export const resourceTypeLabels: Record<CatalogResourceType, string> = {
  exportable: 'Exportable',
  vista: 'Vista',
  tablero: 'Tablero',
  monitoreo: 'Monitoreo',
  reporte: 'Reporte Operativo',
}

export const CATALOG_STATS = {
  principal: navigationCatalog.filter((r) => r.workspace === 'principal').length,
  datosEnLinea: navigationCatalog.filter((r) => r.workspace === 'datos-en-linea').length,
  total: navigationCatalog.length,
} as const
