import {
  BedDouble,
  BookOpenText,
  CalendarRange,
  FileDown,
  FileText,
  FlaskConical,
  Home,
  MonitorDot,
  UsersRound,
} from 'lucide-react'
import { group, item, section } from '@/config/navigation-builders'
import type { NavigationSection, WorkspaceHomeContent, WorkspaceQuickLink } from '@/types/navigation'

const homeItem = item({
  key: 'sigh-home',
  legacyKey: 'inicio',
  legacyRoute: '/sigh/inicio',
  label: 'Inicio',
  to: '/sigh',
  description: 'Entrada principal de Datos en Linea.',
  icon: Home,
})

export const sighSections: NavigationSection[] = [
  section({
    key: 'home',
    title: '',
    entries: [homeItem],
  }),
  section({
    key: 'catalog',
    title: '',
    entries: [
      group({
        key: 'sigh-laboratorio-cultivos',
        legacyKey: 'laboratorio',
        label: 'Laboratorio Cultivos',
        description: 'Consulta visible de laboratorio cultivos.',
        icon: FlaskConical,
        access: { permissions: ['menu.sigh.laboratorio-cultivos.*'] },
        items: [
          item({
            key: 'sigh-mapa-microbiologico',
            legacyKey: 'cultivos',
            legacyRoute: '/sigh/laboratorio/cultivos',
            label: 'Mapa Microbiologico',
            to: '/sigh/laboratorio-cultivos/mapa-microbiologico',
            description: 'Consulta actual del mapa microbiologico.',
            icon: FlaskConical,
            featured: true,
            access: { permissions: ['menu.sigh.laboratorio-cultivos.mapa-microbiologico'] },
          }),
        ],
      }),
      group({
        key: 'sigh-monitoreo-en-linea',
        legacyKey: 'monitoreo',
        label: 'Monitoreo en linea',
        description: 'Consulta visible de monitoreo en linea.',
        icon: MonitorDot,
        access: { permissions: ['menu.sigh.monitoreo-en-linea.*'] },
        items: [
          item({
            key: 'sigh-informe-familia-pendientes',
            legacyKey: 'familiapen',
            legacyRoute: '/sigh/monitoreo/familiapen',
            label: 'Informe Familia Pendientes',
            to: '/sigh/monitoreo-en-linea/informe-familia-pendientes',
            description: 'Consulta actual de informe familia pendientes.',
            icon: MonitorDot,
            featured: true,
            access: { permissions: ['menu.sigh.monitoreo-en-linea.informe-familia-pendientes'] },
          }),
        ],
      }),
      group({
        key: 'sigh-exportar-registros',
        legacyKey: 'exportar',
        label: 'Exportar Registros',
        description: 'Descargas actuales de Datos en Linea.',
        icon: FileDown,
        access: { permissions: ['menu.sigh.exportar-registros.*'] },
        items: [
          item({
            key: 'sigh-registros-nominales',
            legacyKey: 'registros',
            legacyRoute: '/sigh/exportar/registros',
            label: 'Exportar Datos',
            to: '/sigh/exportar-registros/registros-nominales',
            description: 'Reportes diarios de pacientes hospitalizados, altas, fallecidos y camas.',
            icon: FileDown,
            featured: true,
            access: { permissions: ['menu.sigh.exportar-registros.registros-nominales'] },
          }),
          item({
            key: 'sigh-registros-produccion',
            legacyKey: 'exportadata',
            legacyRoute: '/sigh/exportar/exportadata',
            label: 'Zona de Descarga de Información por Periodos',
            to: '/sigh/exportar-registros/registros-produccion',
            description: 'Listados nominales por periodo con validación SISGALEN.',
            icon: FileDown,
            access: { permissions: ['menu.sigh.exportar-registros.registros-produccion'] },
          }),
        ],
      }),
      group({
        key: 'sigh-produccion-actividades',
        legacyKey: 'prodprofesional',
        label: 'Produccion de Actividades',
        description: 'Consulta visible de produccion de actividades.',
        icon: UsersRound,
        access: { permissions: ['menu.sigh.produccion-actividades.*'] },
        items: [
          item({
            key: 'sigh-produccion-medicos',
            legacyKey: 'medico',
            legacyRoute: '/sigh/prodprofesional/medico',
            label: 'Produccion M\u00e9dicos',
            to: '/sigh/produccion-actividades/produccion-medicos',
            description: 'Consulta actual de produccion medica.',
            icon: UsersRound,
            featured: true,
            access: { permissions: ['menu.sigh.produccion-actividades.produccion-medicos'] },
          }),
        ],
      }),
      group({
        key: 'sigh-gestion-camas',
        legacyKey: 'covid',
        label: 'Gestion Camas',
        description: 'Consultas visibles de gestion de camas.',
        icon: BedDouble,
        access: { permissions: ['menu.sigh.gestion-camas.*'] },
        items: [
          item({
            key: 'sigh-monitoreo-camas',
            legacyKey: 'detallecama',
            legacyRoute: '/sigh/covid/detallecama',
            label: 'Monitoreo de Camas',
            to: '/sigh/gestion-camas/monitoreo-de-camas',
            description: 'Consulta actual de monitoreo de camas.',
            icon: BedDouble,
            featured: true,
            access: { permissions: ['menu.sigh.gestion-camas.monitoreo-de-camas'] },
          }),
          item({
            key: 'sigh-resumen-camas',
            legacyKey: 'resumencamas',
            legacyRoute: '/sigh/covid/resumencamas',
            label: 'Resumen de Camas',
            to: '/sigh/gestion-camas/resumen-de-camas',
            description: 'Consulta actual del resumen de camas.',
            icon: BedDouble,
            access: { permissions: ['menu.sigh.gestion-camas.resumen-de-camas'] },
          }),
          item({
            key: 'sigh-porcentaje-ocupacion-cama',
            legacyKey: 'ocupacioncama',
            legacyRoute: '/sigh/covid/ocupacioncama',
            label: 'Porcentaje de Ocupacion Cama',
            to: '/sigh/gestion-camas/porcentaje-de-ocupacion-cama',
            description: 'Consulta actual del porcentaje de ocupacion por cama.',
            icon: BedDouble,
            access: { permissions: ['menu.sigh.gestion-camas.porcentaje-de-ocupacion-cama'] },
          }),
          item({
            key: 'sigh-gestion-estancia-cama',
            legacyKey: 'gestioncama',
            legacyRoute: '/sigh/covid/gestioncama',
            label: 'Gestion Estancia Cama',
            to: '/sigh/gestion-camas/gestion-estancia-cama',
            description: 'Consulta actual de la gestion de estancia por cama.',
            icon: BedDouble,
            featured: true,
            access: { permissions: ['menu.sigh.gestion-camas.gestion-estancia-cama'] },
          }),
        ],
      }),
      group({
        key: 'sigh-atencion-usuario',
        legacyKey: 'gestioncita',
        label: 'Atencion al Usuario',
        description: 'Consultas visibles de atencion al usuario.',
        icon: CalendarRange,
        access: { permissions: ['menu.sigh.atencion-al-usuario.*'] },
        items: [
          item({
            key: 'sigh-gestion-citas',
            legacyKey: 'citalibre',
            legacyRoute: '/sigh/gestioncita/citalibre',
            label: 'Gestion de Citas',
            to: '/sigh/atencion-al-usuario/gestion-de-citas',
            description: 'Consulta actual de gestion de citas.',
            icon: CalendarRange,
            featured: true,
            access: { permissions: ['menu.sigh.atencion-al-usuario.gestion-de-citas'] },
          }),
          item({
            key: 'sigh-rol-consulta-externa',
            legacyKey: 'programacion',
            legacyRoute: '/sigh/gestioncita/programacion',
            label: 'Rol Consulta Externa',
            to: '/sigh/atencion-al-usuario/rol-consulta-externa',
            description: 'Consulta actual del rol de consulta externa.',
            icon: CalendarRange,
            access: { permissions: ['menu.sigh.atencion-al-usuario.rol-consulta-externa'] },
          }),
          item({
            key: 'sigh-monitoreo-tickets',
            legacyKey: 'ventanilla',
            legacyRoute: '/sigh/gestioncita/ventanilla',
            label: 'Monitoreo de Tickets',
            to: '/sigh/atencion-al-usuario/monitoreo-de-tickets',
            description: 'Consulta actual de monitoreo de tickets.',
            icon: CalendarRange,
            access: { permissions: ['menu.sigh.atencion-al-usuario.monitoreo-de-tickets'] },
          }),
          item({
            key: 'sigh-tiempos-espera',
            legacyKey: 'tiempoespera',
            legacyRoute: '/sigh/gestioncita/tiempoespera',
            label: 'Tiempos de Espera',
            to: '/sigh/atencion-al-usuario/tiempos-de-espera',
            description: 'Consulta actual de tiempos de espera.',
            icon: CalendarRange,
            access: { permissions: ['menu.sigh.atencion-al-usuario.tiempos-de-espera'] },
          }),
          item({
            key: 'sigh-monitoreo-ventanilla',
            legacyKey: 'ventanillatmp',
            legacyRoute: '/sigh/gestioncita/ventanillatmp',
            label: 'Monitoreo Ventanilla',
            to: '/sigh/atencion-al-usuario/monitoreo-ventanilla',
            description: 'Consulta actual de monitoreo de ventanilla.',
            icon: CalendarRange,
            access: { permissions: ['menu.sigh.atencion-al-usuario.monitoreo-ventanilla'] },
          }),
        ],
      }),
    ],
  }),
]

export const sighQuickLinks: WorkspaceQuickLink[] = [
  
  {
    key: 'manuales',
    label: 'Ver manuales y tutoriales',
    href: 'https://recursos.heves.gob.pe/',
    description: 'Abre la biblioteca institucional de apoyo al usuario.',
    icon: BookOpenText,
    external: true,
  },
  {
    key: 'formulario',
    label: 'Formulario de solicitud de informacion',
    href: 'https://docs.google.com/forms/d/e/1FAIpQLSe2MFZojk3J2nIPS_UCGmDIHjID3s1qwDb9OYEvG6XwG2fKew/viewform',
    description: 'Permite registrar nuevas solicitudes de informacion.',
    icon: FileText,
    external: true,
  },
]

export const sighHomeContent: WorkspaceHomeContent = {
  title: 'Inicio',
  description: 'Revise los accesos visibles de Datos en Linea y entre directo a los submenus de uso frecuente.',
  featuredTitle: 'Accesos frecuentes',
  featuredDescription: 'Consultas destacadas dentro del menu real actual de Datos en Linea.',
  supportTitle: 'Menu actual de Datos en Linea',
  supportDescription: 'La taxonomia, el orden y los nombres siguen la navegacion real del entorno legacy /sigh.',
}
