export type CatalogWorkspace = 'principal' | 'datos-en-linea'
export type CatalogResourceType = 'exportable' | 'vista' | 'tablero' | 'monitoreo' | 'reporte'

export interface CatalogResource {
  id: string
  title: string
  description: string
  workspace: CatalogWorkspace
  workspaceLabel: string
  type: CatalogResourceType
  category: string
  subcategory?: string
  route: string
  breadcrumb: string
  legacyName?: string
  aliases: string[]
  keywords: string[]
  permissionKey?: string
  featured?: boolean
}

export const navigationCatalog: CatalogResource[] = [
  // ── PRINCIPAL / REPORTEADOR ──────────────────────────────────────────────

  // Indicadores Hospitalarios
  {
    id: 'main-indicadores-eficiencia',
    title: 'Indicadores de Eficiencia',
    description: 'Tablero institucional de indicadores de eficiencia hospitalaria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Indicadores Hospitalarios',
    route: '/app/indicadores-hospitalarios/indicadores-de-eficiencia',
    breadcrumb: 'Reporteador → Indicadores Hospitalarios',
    aliases: ['indicadores', 'eficiencia', 'kpi'],
    keywords: ['indicador', 'eficiencia', 'hospitalario', 'tablero', 'powerbi'],
    permissionKey: 'menu.main.indicadores-hospitalarios.eficiencia',
    featured: true,
  },
  {
    id: 'main-indicadores-eficacia',
    title: 'Indicadores de Eficacia',
    description: 'Tablero institucional de indicadores de eficacia hospitalaria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Indicadores Hospitalarios',
    route: '/app/indicadores-hospitalarios/indicadores-de-eficacia',
    breadcrumb: 'Reporteador → Indicadores Hospitalarios',
    aliases: ['indicadores', 'eficacia', 'kpi'],
    keywords: ['indicador', 'eficacia', 'hospitalario', 'tablero'],
    permissionKey: 'menu.main.indicadores-hospitalarios.eficacia',
  },
  {
    id: 'main-indicadores-calidad',
    title: 'Indicadores de Calidad',
    description: 'Tablero institucional de indicadores de calidad hospitalaria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Indicadores Hospitalarios',
    route: '/app/indicadores-hospitalarios/indicadores-de-calidad',
    breadcrumb: 'Reporteador → Indicadores Hospitalarios',
    aliases: ['indicadores', 'calidad', 'kpi'],
    keywords: ['indicador', 'calidad', 'hospitalario', 'tablero'],
    permissionKey: 'menu.main.indicadores-hospitalarios.calidad',
  },

  // Atención Ambulatoria y Hospitalización
  {
    id: 'main-consulta-externa',
    title: 'Consulta Externa',
    description: 'Producción y monitoreo de consulta externa ambulatoria.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['ambulatoria', 'ce', 'consultorios'],
    keywords: ['consulta', 'externa', 'ambulatoria', 'produccion', 'citas'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa',
  },
  {
    id: 'main-consulta-externa-servicio',
    title: 'Consulta Externa por Servicio',
    description: 'Producción de consulta externa desagregada por servicio.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-por-servicio',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['consulta externa servicio', 'ce servicio'],
    keywords: ['consulta', 'externa', 'servicio', 'especialidad', 'produccion'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-por-servicio',
  },
  {
    id: 'main-consulta-externa-consultorio-profesional',
    title: 'Consulta Externa por Consultorio y Profesional',
    description: 'Vista de producción por consultorio y profesional de salud.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'vista',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-por-por-consultorio-y-profesional',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['consultorio profesional', 'medico consultorio'],
    keywords: ['consulta', 'externa', 'consultorio', 'profesional', 'medico'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-por-consultorio-profesional',
  },
  {
    id: 'main-consulta-externa-monitoreo',
    title: 'Consulta Externa — Monitoreo',
    description: 'Monitoreo en tiempo real de la consulta externa.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-monitoreo',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['monitoreo ce', 'seguimiento consulta'],
    keywords: ['monitoreo', 'consulta', 'externa', 'tiempo real'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-monitoreo',
  },
  {
    id: 'main-consulta-externa-diagnosticos',
    title: 'Consulta Externa — Diagnósticos Frecuentes',
    description: 'Diagnósticos más frecuentes en consulta externa.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/consulta-externa-diagnosticos-frecuentes',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['diagnosticos frecuentes', 'cie10', 'morbilidad ambulatoria'],
    keywords: ['diagnostico', 'frecuente', 'consulta', 'externa', 'cie'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.consulta-externa-diagnosticos-frecuentes',
  },
  {
    id: 'main-hospitalizacion',
    title: 'Hospitalización',
    description: 'Indicadores de hospitalización: ocupación, estancia y producción.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/hospitalizacion',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['hospitalizados', 'internados', 'camas hospitalización', 'pacientes internados'],
    keywords: ['hospitalizacion', 'hospitalizados', 'internados', 'cama', 'estancia', 'ocupacion'],
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.hospitalizacion',
    featured: true,
  },
  {
    id: 'main-centro-obstetrico',
    title: 'Centro Obstétrico',
    description: 'Indicadores obstétricos: partos, cesáreas y morbilidad materna.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Atención Ambulatoria y Hospitalización',
    route: '/app/atencion-ambulatoria-hospitalizacion/centro-obstetrico',
    breadcrumb: 'Reporteador → Atención Ambulatoria y Hospitalización',
    aliases: ['obstetrico', 'partos', 'cesarea', 'maternidad', 'morbilidad materna', 'bai', 'BAI morbilidad materna extrema'],
    keywords: ['obstetrico', 'parto', 'cesarea', 'maternidad', 'morbilidad', 'materna', 'BAI', 'bai'],
    legacyName: 'BAI - Morbilidad Materna Extrema',
    permissionKey: 'menu.main.atencion-ambulatoria-hospitalizacion.centro-obstetrico',
    featured: true,
  },

  // Emergencia y Cuidados Críticos
  {
    id: 'main-triaje-admisionados',
    title: 'Triaje Admisionados',
    description: 'Listado nominal de ingresos nuevos en servicios de emergencia.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/triaje-admisionados',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    legacyName: 'Listado Nominal de Ingresos Nuevos en los Servicios de Emergencia',
    aliases: ['admisionados emergencia', 'ingresos emergencia', 'triaje', 'admitidos'],
    keywords: ['triaje', 'admisionado', 'ingreso', 'emergencia', 'listado', 'nominal'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.triaje-admisionados',
  },
  {
    id: 'main-emergencia',
    title: 'Emergencia',
    description: 'Producción general del servicio de emergencia.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/emergencia',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['urgencias', 'emergencias'],
    keywords: ['emergencia', 'urgencia', 'produccion'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.emergencia',
  },
  {
    id: 'main-emergencia-por-servicio',
    title: 'Emergencia por Servicio',
    description: 'Producción del servicio de emergencia por especialidad.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/emergencia-por-servicio',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['emergencia servicio', 'urgencias especialidad'],
    keywords: ['emergencia', 'servicio', 'especialidad', 'produccion'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.emergencia-por-servicio',
  },
  {
    id: 'main-cuidados-criticos',
    title: 'Cuidados Críticos UCE y UCI',
    description: 'Indicadores de Unidad de Cuidados Críticos (UCE adulto y UCI).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/cuidados-criticos-uce-y-uci',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['uci', 'uce', 'unidad cuidados intensivos', 'criticos'],
    keywords: ['cuidados', 'criticos', 'uci', 'uce', 'intensivos'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.cuidados-criticos-uce-y-uci',
    featured: true,
  },
  {
    id: 'main-indicadores-ucca',
    title: 'Indicadores UCCA (Adulto)',
    description: 'Indicadores de la Unidad de Cuidados Críticos Adulto.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/indicadores-ucca',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['ucca', 'cuidados criticos adulto'],
    keywords: ['ucca', 'adulto', 'cuidados', 'criticos', 'indicadores'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.indicadores-ucca',
  },
  {
    id: 'main-indicadores-uccp',
    title: 'Indicadores UCCP (Pediátrico)',
    description: 'Indicadores de la Unidad de Cuidados Críticos Pediátrico.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/indicadores-uccp',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['uccp', 'cuidados criticos pediatrico', 'pediatrico critico'],
    keywords: ['uccp', 'pediatrico', 'cuidados', 'criticos', 'indicadores'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.indicadores-uccp',
  },
  {
    id: 'main-centro-quirurgico',
    title: 'Centro Quirúrgico',
    description: 'Producción del centro quirúrgico: cirugías y procedimientos.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Emergencia y Cuidados Críticos',
    route: '/app/emergencia-cuidados-criticos/centro-quirurgico',
    breadcrumb: 'Reporteador → Emergencia y Cuidados Críticos',
    aliases: ['quirurgico', 'cirugias', 'sala de operaciones', 'sop'],
    keywords: ['quirurgico', 'cirugia', 'operaciones', 'produccion', 'sala'],
    permissionKey: 'menu.main.emergencia-cuidados-criticos.centro-quirurgico',
  },

  // Apoyo al Diagnóstico y Tratamiento
  {
    id: 'main-laboratorio',
    title: 'Laboratorio',
    description: 'Producción del laboratorio clínico.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Apoyo al Diagnóstico y Tratamiento',
    route: '/app/apoyo-diagnostico-tratamiento/laboratorio',
    breadcrumb: 'Reporteador → Apoyo al Diagnóstico y Tratamiento',
    aliases: ['lab', 'analisis clinico', 'laboratorio clinico'],
    keywords: ['laboratorio', 'analisis', 'clinico', 'muestra', 'resultado'],
    permissionKey: 'menu.main.apoyo-diagnostico-tratamiento.laboratorio',
    featured: true,
  },
  {
    id: 'main-imagenologia',
    title: 'Imagenología',
    description: 'Producción del servicio de imagenología: rayos X, ecografías, etc.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Apoyo al Diagnóstico y Tratamiento',
    route: '/app/apoyo-diagnostico-tratamiento/imagenologia',
    breadcrumb: 'Reporteador → Apoyo al Diagnóstico y Tratamiento',
    aliases: ['imagenes', 'rayos x', 'ecografia', 'radiologia'],
    keywords: ['imagenologia', 'rayos', 'ecografia', 'radiologia', 'imagen'],
    permissionKey: 'menu.main.apoyo-diagnostico-tratamiento.imagenologia',
  },

  // Unidad de Calidad
  {
    id: 'main-incidentes-eventos-adversos',
    title: 'Notificación de Incidentes y Eventos Adversos',
    description: 'Registro y seguimiento de incidentes clínicos y eventos adversos.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Unidad de Calidad',
    route: '/app/unidad-calidad/notificacion-incidentes-eventos-adversos',
    breadcrumb: 'Reporteador → Unidad de Calidad',
    aliases: ['eventos adversos', 'incidentes', 'calidad', 'seguridad paciente'],
    keywords: ['incidente', 'evento', 'adverso', 'calidad', 'seguridad', 'notificacion'],
    permissionKey: 'menu.main.unidad-calidad.incidentes-eventos-adversos',
  },

  // Neonatología
  {
    id: 'main-tamizaje-neonatal',
    title: 'Tamizaje Neonatal — Enfermería',
    description: 'Registro de tamizaje neonatal realizado por enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Neonatología',
    route: '/app/neonatologia/tamizaje-neonatal-enfermeria',
    breadcrumb: 'Reporteador → Neonatología',
    aliases: ['neonato', 'tamizaje neonatal', 'recien nacido'],
    keywords: ['tamizaje', 'neonatal', 'enfermeria', 'neonato', 'nacido'],
    permissionKey: 'menu.main.neonatologia.tamizaje-neonatal',
  },
  {
    id: 'main-extraccion-lm',
    title: 'Extracción LM — Enfermería',
    description: 'Registro de extracción de leche materna por enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Neonatología',
    route: '/app/neonatologia/extraccion-lm-enfermeria',
    breadcrumb: 'Reporteador → Neonatología',
    aliases: ['lactancia materna', 'leche materna', 'extraccion lm'],
    keywords: ['extraccion', 'leche', 'materna', 'lactancia', 'neonato', 'enfermeria'],
    permissionKey: 'menu.main.neonatologia.extraccion-lm',
  },

  // Hechos Vitales
  {
    id: 'main-defunciones',
    title: 'Defunciones',
    description: 'Tablero de hechos vitales: defunciones y fallecidos.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Hechos Vitales',
    route: '/app/hechos-vitales/defunciones',
    breadcrumb: 'Reporteador → Hechos Vitales',
    aliases: ['fallecidos', 'muertes', 'defunciones', 'obituario', 'reporte diario fallecidos'],
    keywords: ['defuncion', 'fallecido', 'muerte', 'vital', 'obituario'],
    permissionKey: 'menu.main.hechos-vitales.defunciones',
    featured: true,
  },
  {
    id: 'main-inconsistencia-cdef',
    title: 'Inconsistencia CDEF',
    description: 'Inconsistencias en registros de certificados de defunción (CDEF).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Hechos Vitales',
    route: '/app/hechos-vitales/inconsistencia-cdef',
    breadcrumb: 'Reporteador → Hechos Vitales',
    aliases: ['cdef', 'certificado defuncion', 'inconsistencias'],
    keywords: ['cdef', 'certificado', 'defuncion', 'inconsistencia'],
    permissionKey: 'menu.main.hechos-vitales.inconsistencia-cdef',
  },
  {
    id: 'main-nacimientos',
    title: 'Nacimientos',
    description: 'Registro y estadísticas de nacimientos institucionales.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Hechos Vitales',
    route: '/app/hechos-vitales/nacimientos',
    breadcrumb: 'Reporteador → Hechos Vitales',
    aliases: ['partos', 'nacidos', 'nuevos nacimientos'],
    keywords: ['nacimiento', 'parto', 'nacido', 'vital'],
    permissionKey: 'menu.main.hechos-vitales.nacimientos',
  },

  // Sala Inteligente
  {
    id: 'main-sala-inteligente-emergencia',
    title: 'Indicadores de Emergencia',
    description: 'Indicadores en tiempo real del servicio de emergencia (Sala Inteligente).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/indicadores-de-emergencia',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['sala inteligente emergencia', 'monitoreo emergencia'],
    keywords: ['sala', 'inteligente', 'indicadores', 'emergencia', 'monitoreo'],
    permissionKey: 'menu.main.sala-inteligente.indicadores-de-emergencia',
  },
  {
    id: 'main-sala-inteligente-referencia-ce',
    title: 'Referencia de Consulta Externa',
    description: 'Seguimiento de referencias y contrarreferencias de consulta externa.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/referencia-de-consulta-externa',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['referencias ce', 'contrarreferencias consulta', 'referencia ambulatoria'],
    keywords: ['referencia', 'contrarreferencia', 'consulta', 'externa'],
    permissionKey: 'menu.main.sala-inteligente.referencia-de-consulta-externa',
  },
  {
    id: 'main-sala-inteligente-referencia-emergencia',
    title: 'Referencia de Emergencia',
    description: 'Seguimiento de referencias y contrarreferencias de emergencia.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/referencia-de-emergencia',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['referencias emergencia', 'contrarreferencias urgencias'],
    keywords: ['referencia', 'contrarreferencia', 'emergencia', 'urgencia'],
    permissionKey: 'menu.main.sala-inteligente.referencia-de-emergencia',
  },
  {
    id: 'main-sala-inteligente-interconsulta',
    title: 'Interconsulta Hospitalaria',
    description: 'Monitoreo de interconsultas entre servicios hospitalarios.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/interconsulta-hospitalaria',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['interconsulta', 'interconsultas', 'consulta entre servicios'],
    keywords: ['interconsulta', 'hospitalaria', 'servicio', 'consulta'],
    permissionKey: 'menu.main.sala-inteligente.interconsulta-hospitalaria',
  },
  {
    id: 'main-sala-inteligente-enfermeria',
    title: 'Indicadores de Enfermería',
    description: 'Indicadores de desempeño del servicio de enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/indicadores-de-enfermeria',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['enfermeria', 'indicadores enfermeria'],
    keywords: ['enfermeria', 'indicadores', 'sala', 'inteligente'],
    permissionKey: 'menu.main.sala-inteligente.indicadores-de-enfermeria',
  },
  {
    id: 'main-sala-inteligente-pacientes-hospitalizados',
    title: 'Pacientes Hospitalizados',
    description: 'Monitoreo en línea de pacientes hospitalizados por piso y servicio.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/pacientes-hospitalizados',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['hospitalizados', 'pacientes internados', 'estancia hospitalaria', 'pacientes cama'],
    keywords: ['paciente', 'hospitalizado', 'internado', 'estancia', 'cama', 'piso'],
    permissionKey: 'menu.main.sala-inteligente.pacientes-hospitalizados',
    featured: true,
  },
  {
    id: 'main-sala-inteligente-continuadores',
    title: 'Pacientes Continuadores',
    description: 'Seguimiento de pacientes continuadores en consulta externa.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/pacientes-continuadores',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['continuadores', 'pacientes continuadores'],
    keywords: ['paciente', 'continuador', 'consulta', 'seguimiento'],
    permissionKey: 'menu.main.sala-inteligente.pacientes-continuadores',
  },
  {
    id: 'main-sala-inteligente-isq',
    title: 'Indicadores de ISQ — Endometritis',
    description: 'Indicadores de infección de sitio quirúrgico y endometritis.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'tablero',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/indicadores-de-isq-endometritis',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['isq', 'endometritis', 'infeccion quirurgica', 'infeccion sitio quirurgico'],
    keywords: ['isq', 'endometritis', 'infeccion', 'quirurgico', 'indicadores'],
    permissionKey: 'menu.main.sala-inteligente.indicadores-de-isq-endometritis',
  },
  {
    id: 'main-sala-inteligente-vacunas',
    title: 'Vacunas — Enfermería',
    description: 'Registro de aplicación de vacunas por el servicio de enfermería.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/vacunas-enfermeria',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['vacunas', 'inmunizacion', 'vacunacion'],
    keywords: ['vacuna', 'inmunizacion', 'vacunacion', 'enfermeria'],
    permissionKey: 'menu.main.sala-inteligente.vacunas-enfermeria',
  },
  {
    id: 'main-sala-inteligente-iaas',
    title: 'Monitoreo de IAAS',
    description: 'Monitoreo de Infecciones Asociadas a la Atención en Salud (IAAS).',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Sala Inteligente',
    route: '/app/sala-inteligente/monitoreo-de-iaas',
    breadcrumb: 'Reporteador → Sala Inteligente',
    aliases: ['iaas', 'infecciones hospitalarias', 'nosocomiales', 'iras nosocomiales'],
    keywords: ['iaas', 'infeccion', 'hospitalaria', 'nosocomial', 'atencion', 'salud', 'monitoreo'],
    permissionKey: 'menu.main.sala-inteligente.monitoreo-de-iaas',
  },

  // Monitoreo Salud Mental
  {
    id: 'main-salud-mental-reportes',
    title: 'Reportes Monitoreo — Salud Mental',
    description: 'Reportes de monitoreo en salud mental: violencia, ansiedad, depresión, etc.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Monitoreo Salud Mental',
    route: '/app/monitoreo-salud-mental/reportes-monitoreo',
    breadcrumb: 'Reporteador → Monitoreo Salud Mental',
    aliases: ['salud mental', 'psiquiatria', 'psicologia', 'violencia', 'ansiedad', 'depresion', 'conducta', 'mental'],
    keywords: ['salud', 'mental', 'reporte', 'monitoreo', 'violencia', 'ansiedad', 'depresion', 'psiquiatria', 'psicologia'],
    permissionKey: 'menu.main.monitoreo-salud-mental.reportes-monitoreo',
    featured: true,
  },
  {
    id: 'main-tamizaje-salud-mental',
    title: 'Tamizaje Salud Mental',
    description: 'Tamizaje de salud mental: PHQ-9, GAD-7 y otras escalas.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Monitoreo Salud Mental',
    route: '/app/monitoreo-salud-mental/tamizaje-salud-mental',
    breadcrumb: 'Reporteador → Monitoreo Salud Mental',
    aliases: ['tamizaje mental', 'phq', 'gad', 'cribado mental', 'salud mental tamizaje'],
    keywords: ['tamizaje', 'salud', 'mental', 'phq', 'gad', 'escala', 'cribado'],
    permissionKey: 'menu.main.monitoreo-salud-mental.tamizaje-salud-mental',
  },

  // Zona de Descarga / Exportar Datos
  {
    id: 'main-registros-procesados',
    title: 'Exportar Datos — Registros Procesados',
    description: 'Exportación de datos institucionales incluyendo BAI - Morbilidad Materna Extrema y otros registros procesados.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Zona de Descarga',
    route: '/app/zona-descarga/registros-procesados',
    breadcrumb: 'Reporteador → Zona de Descarga',
    legacyName: 'Exportar Datos / BAI - Morbilidad Materna Extrema',
    aliases: ['exportar datos', 'registros', 'descarga', 'bai', 'morbilidad materna', 'exportar registros procesados'],
    keywords: ['exportar', 'datos', 'registro', 'descarga', 'bai', 'morbilidad', 'materna', 'procesado'],
    permissionKey: 'menu.main.zona-descarga.registros-procesados',
    featured: true,
  },

  // Articulación Prestacional
  {
    id: 'main-monitoreo-citas',
    title: 'Monitoreo de Citas',
    description: 'Monitoreo de la programación y asignación de citas médicas.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'monitoreo',
    category: 'Articulación Prestacional',
    route: '/app/articulacion-prestacional/monitoreo-de-citas',
    breadcrumb: 'Reporteador → Articulación Prestacional',
    aliases: ['citas medicas', 'agenda medica', 'programacion citas'],
    keywords: ['cita', 'medica', 'programacion', 'monitoreo', 'agenda'],
    permissionKey: 'menu.main.articulacion-prestacional.monitoreo-de-citas',
    featured: true,
  },
  {
    id: 'main-citas-reprogramadas',
    title: 'Indicador Citas Reprogramadas',
    description: 'Indicador de citas reprogramadas para seguimiento de demanda.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Articulación Prestacional',
    route: '/app/articulacion-prestacional/indicador-citas-reprogramdas',
    breadcrumb: 'Reporteador → Articulación Prestacional',
    aliases: ['citas reprogramadas', 'reprogramadas', 'indicador citas'],
    keywords: ['cita', 'reprogramada', 'indicador', 'demanda'],
    permissionKey: 'menu.main.articulacion-prestacional.indicador-citas-reprogramdas',
  },

  // Epidemiología
  {
    id: 'main-lavado-manos',
    title: 'Lavado de Manos',
    description: 'Exportación de registros de lavado de manos para vigilancia epidemiológica.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'exportable',
    category: 'Epidemiología',
    route: '/app/epidemiologia/lavado-de-manos',
    breadcrumb: 'Reporteador → Epidemiología',
    legacyName: 'Registro de Lavado de Manos — Exportar',
    aliases: ['lavado manos', 'higiene manos', 'epidemiologia lavado', 'registro lavado'],
    keywords: ['lavado', 'manos', 'higiene', 'epidemiologia', 'registro', 'exportar'],
    permissionKey: 'menu.main.epidemiologia.lavado-de-manos',
    featured: true,
  },
  {
    id: 'main-accidente-transito',
    title: 'Accidente de Tránsito',
    description: 'Registro epidemiológico de pacientes lesionados en accidentes de tránsito.',
    workspace: 'principal',
    workspaceLabel: 'Reporteador',
    type: 'reporte',
    category: 'Epidemiología',
    route: '/app/epidemiologia/accidente-de-transito',
    breadcrumb: 'Reporteador → Epidemiología',
    aliases: ['accidente transito', 'lesionados', 'accidentados'],
    keywords: ['accidente', 'transito', 'lesionado', 'epidemiologia'],
    permissionKey: 'menu.main.epidemiologia.accidente-de-transito',
  },

  // ── DATOS EN LÍNEA / SIGH ───────────────────────────────────────────────

  // Laboratorio Cultivos
  {
    id: 'sigh-mapa-microbiologico',
    title: 'Mapa Microbiológico',
    description: 'Mapa microbiológico del laboratorio de cultivos.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'vista',
    category: 'Laboratorio Cultivos',
    route: '/sigh/laboratorio-cultivos/mapa-microbiologico',
    breadcrumb: 'Datos en Línea → Laboratorio Cultivos',
    aliases: ['cultivos', 'microbiologia', 'antibiograma', 'resistencia bacteriana'],
    keywords: ['mapa', 'microbiologico', 'cultivo', 'laboratorio', 'bacteria', 'resistencia'],
    permissionKey: 'menu.sigh.laboratorio-cultivos.mapa-microbiologico',
  },

  // Monitoreo en Línea
  {
    id: 'sigh-informe-familia-pendientes',
    title: 'Informe Familia Pendientes',
    description: 'Monitoreo de informes familiares pendientes de atención.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Monitoreo en Línea',
    route: '/sigh/monitoreo-en-linea/informe-familia-pendientes',
    breadcrumb: 'Datos en Línea → Monitoreo en Línea',
    aliases: ['familia pendientes', 'informe familiar', 'pendientes familia'],
    keywords: ['informe', 'familia', 'pendiente', 'monitoreo'],
    permissionKey: 'menu.sigh.monitoreo-en-linea.informe-familia-pendientes',
    featured: true,
  },

  // Exportar Registros
  {
    id: 'sigh-registros-nominales',
    title: 'Exportar Datos — Registros Nominales Diarios',
    description: 'Reportes diarios de pacientes hospitalizados, altas, fallecidos, camas y apertura de cuentas.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'exportable',
    category: 'Exportar Registros',
    route: '/sigh/exportar-registros/registros-nominales',
    breadcrumb: 'Datos en Línea → Exportar Registros',
    legacyName: 'Exportar Datos (registros nominales)',
    aliases: [
      'exportar datos',
      'hospitalizados',
      'altas',
      'fallecidos',
      'camas diario',
      'reporte diario hospitalizados',
      'reporte diario pacientes hospitalizados',
      'reporte diario pacientes alta',
      'reporte diario pacientes fallecidos',
      'reporte diario camas',
      'listado nominal fallecidos',
      'listado nominal altas',
      'listado nominal alta medica',
      'apertura cuentas',
      'listado usuarios apertura cuentas',
    ],
    keywords: ['exportar', 'datos', 'hospitalizado', 'alta', 'fallecido', 'cama', 'diario', 'nominal', 'apertura', 'cuenta'],
    permissionKey: 'menu.sigh.exportar-registros.registros-nominales',
    featured: true,
  },
  {
    id: 'sigh-registros-produccion',
    title: 'Zona de Descarga de Información por Periodos',
    description: 'Listados nominales por periodo con validación SISGALEN: programados, atendidos, emergencias, altas, fallecidos, historias clínicas.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'exportable',
    category: 'Exportar Registros',
    route: '/sigh/exportar-registros/registros-produccion',
    breadcrumb: 'Datos en Línea → Exportar Registros',
    legacyName: 'Zona de Descarga de Información por Periodos',
    aliases: [
      'zona descarga',
      'descarga periodos',
      'historias clinicas',
      'historias clinicas aperturadas',
      'recetas firma electronica',
      'firma electronica',
      'listado nominal programados',
      'listado nominal atendidos',
      'listado nominal emergencia',
      'ambulatorio nominal',
      'sisgalen',
      'hce',
    ],
    keywords: ['zona', 'descarga', 'periodo', 'nominal', 'historia', 'clinica', 'receta', 'firma', 'electronica', 'sisgalen', 'programado', 'atendido'],
    permissionKey: 'menu.sigh.exportar-registros.registros-produccion',
    featured: true,
  },

  // Producción de Actividades
  {
    id: 'sigh-produccion-medicos',
    title: 'Producción Médicos',
    description: 'Producción de actividades de médicos: consultas, procedimientos. Exportable en PDF y Excel.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'exportable',
    category: 'Producción de Actividades',
    route: '/sigh/produccion-actividades/produccion-medicos',
    breadcrumb: 'Datos en Línea → Producción de Actividades',
    legacyName: 'Producción Médicos — PDF / Excel',
    aliases: [
      'produccion medicos',
      'produccion medica',
      'produccion pdf',
      'produccion excel',
      'medicos pdf',
      'medicos excel',
      'actividades medicos',
    ],
    keywords: ['produccion', 'medico', 'actividad', 'pdf', 'excel', 'exportar'],
    permissionKey: 'menu.sigh.produccion-actividades.produccion-medicos',
    featured: true,
  },

  // Gestión Camas
  {
    id: 'sigh-monitoreo-camas',
    title: 'Monitoreo de Camas',
    description: 'Monitoreo en tiempo real del estado de camas hospitalarias.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/monitoreo-de-camas',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    aliases: ['monitoreo camas', 'camas tiempo real', 'estado camas', 'ocupacion camas'],
    keywords: ['monitoreo', 'cama', 'ocupacion', 'disponible', 'tiempo', 'real'],
    permissionKey: 'menu.sigh.gestion-camas.monitoreo-de-camas',
    featured: true,
  },
  {
    id: 'sigh-resumen-camas',
    title: 'Resumen de Camas',
    description: 'Resumen de camas por piso y servicio incluyendo Susalud.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'tablero',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/resumen-de-camas',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    legacyName: 'Resumen por Piso / Resumen Susalud',
    aliases: ['resumen camas', 'resumen piso', 'susalud', 'camas por piso', 'camas susalud'],
    keywords: ['resumen', 'cama', 'piso', 'susalud', 'disponible'],
    permissionKey: 'menu.sigh.gestion-camas.resumen-de-camas',
  },
  {
    id: 'sigh-ocupacion-cama',
    title: 'Porcentaje de Ocupación Cama',
    description: 'Porcentaje de ocupación de camas por servicio y periodo.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'tablero',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/porcentaje-de-ocupacion-cama',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    aliases: ['ocupacion cama', 'porcentaje camas', 'camas ocupadas'],
    keywords: ['ocupacion', 'cama', 'porcentaje', 'disponible'],
    permissionKey: 'menu.sigh.gestion-camas.porcentaje-de-ocupacion-cama',
  },
  {
    id: 'sigh-gestion-estancia-cama',
    title: 'Gestión Estancia Cama',
    description: 'Gestión de estancia por cama: días hospitalizados y rotación.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'tablero',
    category: 'Gestión de Camas',
    route: '/sigh/gestion-camas/gestion-estancia-cama',
    breadcrumb: 'Datos en Línea → Gestión de Camas',
    aliases: ['estancia cama', 'dias cama', 'rotacion cama', 'gestion estancia'],
    keywords: ['estancia', 'cama', 'dias', 'rotacion', 'gestion'],
    permissionKey: 'menu.sigh.gestion-camas.gestion-estancia-cama',
    featured: true,
  },

  // Atención al Usuario
  {
    id: 'sigh-gestion-citas',
    title: 'Gestión de Citas',
    description: 'Monitoreo de la gestión de citas médicas y disponibilidad.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/gestion-de-citas',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['gestion citas', 'citas disponibles', 'agenda citas'],
    keywords: ['gestion', 'cita', 'disponible', 'agenda', 'programacion'],
    permissionKey: 'menu.sigh.atencion-al-usuario.gestion-de-citas',
    featured: true,
  },
  {
    id: 'sigh-rol-consulta-externa',
    title: 'Rol Consulta Externa',
    description: 'Rol y programación de consulta externa por especialidad.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'vista',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/rol-consulta-externa',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['rol consulta', 'programacion consulta', 'rol medico'],
    keywords: ['rol', 'consulta', 'externa', 'programacion', 'especialidad'],
    permissionKey: 'menu.sigh.atencion-al-usuario.rol-consulta-externa',
  },
  {
    id: 'sigh-monitoreo-tickets',
    title: 'Monitoreo de Tickets',
    description: 'Monitoreo de tickets de ventanilla y atención al usuario.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/monitoreo-de-tickets',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    legacyName: 'Listado de Ticket de Ventanilla',
    aliases: ['tickets', 'ticket ventanilla', 'ticket admision', 'colas', 'turno', 'cola espera'],
    keywords: ['ticket', 'ventanilla', 'admision', 'cola', 'turno', 'monitoreo'],
    permissionKey: 'menu.sigh.atencion-al-usuario.monitoreo-de-tickets',
    featured: true,
  },
  {
    id: 'sigh-tiempos-espera',
    title: 'Tiempos de Espera',
    description: 'Monitoreo de tiempos de espera en ventanilla y consulta.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/tiempos-de-espera',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['tiempo espera', 'espera pacientes', 'demora atencion'],
    keywords: ['tiempo', 'espera', 'ventanilla', 'demora', 'atencion'],
    permissionKey: 'menu.sigh.atencion-al-usuario.tiempos-de-espera',
  },
  {
    id: 'sigh-monitoreo-ventanilla',
    title: 'Monitoreo Ventanilla',
    description: 'Monitoreo operativo de ventanilla de admisión y citas.',
    workspace: 'datos-en-linea',
    workspaceLabel: 'Datos en Línea',
    type: 'monitoreo',
    category: 'Atención al Usuario',
    route: '/sigh/atencion-al-usuario/monitoreo-ventanilla',
    breadcrumb: 'Datos en Línea → Atención al Usuario',
    aliases: ['ventanilla', 'admision', 'monitoreo admision'],
    keywords: ['ventanilla', 'admision', 'monitoreo', 'atencion', 'usuario'],
    permissionKey: 'menu.sigh.atencion-al-usuario.monitoreo-ventanilla',
  },

]

export const resourceTypeLabels: Record<CatalogResourceType, string> = {
  exportable: 'Exportable',
  vista: 'Vista',
  tablero: 'Tablero',
  monitoreo: 'Monitoreo',
  reporte: 'Reporte Operativo',
}

export const CATALOG_STATS = {
  principal: navigationCatalog.filter((r) => r.workspace === 'principal').length,
  datosEnLinea: navigationCatalog.filter((r) => r.workspace === 'datos-en-linea').length,
  total: navigationCatalog.length,
} as const
